<?php global $pseudo_directory_offset; $site_file_store = $pseudo_directory_offset."attachments/sites/default/"; 
$oscailt_page_setting = Array("site_module_settings" => Array("siteobject" => "1", "newswireobject" => "2126", "articleobject" => "53", "featureobject" => "54", "galleryobject" => "64", "searchobject" => "2212", "archiveobject" => "55", "contactobject" => "84", "commentsobject" => "", "publishobject" => "57", "eventsobject" => "58"), "site_mail_settings" => Array("to" => "news@imemc.org", "from" => "site@imemc.org", "subject_prefix" => "Article edit:", "replyto" => "news@imemc.org", "level" => "none"), "site_filters" => Array("topic" => Array("0" => "*"), "region" => Array("0" => "20", "1" => "19", "2" => "18", "3" => "17", "4" => "16", "5" => "15", "6" => "14", "7" => "13", "8" => "12", "9" => "11", "10" => "10", "11" => "9", "12" => "8", "13" => "7", "14" => "6", "15" => "5", "16" => "4", "17" => "3", "18" => "2", "19" => "1"), "language" => Array("0" => "en"), "type" => Array("0" => "*"), "author" => ""), "obj_id" => "2124", "obj_type" => "DOCUMENT", "site_id" => "1");
$oscailt_story_query = new StoryQuery();
$oscailt_story_query->loadFormValues();
$PAGE_LAYOUT_ID = 2032; ?>
<?
         addToPageDescription("The IMEMC is a media collective. We are independent journalists producing and distributing the authentic voices of the people.  We are located in Beit Sahour, in the Occupied West Bank, and we welcome new volunteers and contributors.");
      addToPageTitle("Donaciones To IMEMC");
         addToPageDescription("Apoya la continuacion del proyecto de IMEMC"); ?>

<!-- <Donaciones to IMEMC obj id 2124> -->
<h1 class='indypagebody'>Apoya la continuacion del proyecto de IMEMC</h1><BLOCKQUOTE class='indypagebody'>Desde que el IMEMC existe como proyecto del Rapprochement Center, su cuenta bancaria no ha cambiado. Asi, puedes indicar que la donacion se dirige al IMEMC cuando hagas el ingreso.</BLOCKQUOTE><DIV class='indypagebody'><center>
<a href="http://www.pcr.ps/donate.htm" target="_blank"><img src="http://images.clickandpledge.com/flair/buttons/97x84/CP_EN_OR_A_001.gif"><br />
Click here to donate securely to IMEMC</a>
</center>

Para donaciones directas en la cuenta bancaria del PCR en Estados Unidos, por favor realiza el ingreso en: <br /><br />
Pay to: JPMORGAN CHASE BANK <br />
SWIFT CODE: CHASUS33 NEW YORK, USA <br /><br />

A/C OF: ARAB JORDAN INVESTMENT BANK <br />
SWIFT CODE: AJIBJOAX <br />
AMMAN, JORDAN<br /><br />

BEN BANK: PALESTINE INVESTMENT BANK <br />
A/C: 6171 <br />
RAMALA, PALESTINE <br /><br />
Bank Number: 76<br />
Branch Number: 411<br />
BEN NAME: (The Palestinian Center For Rapprochement Between People) <br />
BEN A/C NO (78244)<br /><br />

Para donaciones a la cuenta de PCR en Gran Bretana, utiliza la siguiente informaciÃ?Â³n bancaria:<br /><br />
HSBC BK<br />
PLC LONDON <br />
SWIFT CODE: MIDLGB22<br /><br />

A/C ARAB JORDAN INVESTMENT BANK<br />
AMMAN -JORDAN- AL SHMASANEE<br />
SWIFT CODE: AJIBJOAX<br /><br />

BEN BANK: PALESTINE INVESTMENT BANK<br />
A/C: 6171 <br />
RAMALA, PALESTINE <br /><br />
Bank Number: 76<br />
Branch Number: 411<br />
BEN NAME: (The Palestinian Center for Rapprochement Between People)<br />
BEN A/C NO (78244)<br />
BENADDRESS: SCHOOLS STREET, P.O.BOX 24, BEIT SAHOUR, PALESTINE<br /><br />

Para donaciones realizadas desde cualquier paÃ?Â­Ã?Â­s europeo en EUROS, utiliza la siguiente informaciÃ?Â³n bancaria:
<br /><br />

Pay to: DEUTSCHE BANK <br />
SWIFT CODE: DEUTDEFF<br />
IBAN: DE60500700100954019610 <br /><br />

A/C OF: ARAB JORDAN INVESTMENT BANK <br />
SWIFT CODE: AJIBJOAX <br />
AMMAN - JORDAN<br /><br />

BEN BANK: PALESTINE INVESTMENT BANK <br />
A/C: 6171 <br />
RAMALA - PALESTINE <br /><br />
Bank Number: 76<br />
Branch Number: 411<br />
BEN NAME: (The Palestinian Center for Rapprochement between People) <br />
BEN A/C NO (78244) <br /><br />

Si tienes cualquier consulta que hacernos no dudes en contactarnos a nuestro correo electrÃ?Â³nico <a href="mailto:donate@imemc.org">donate@imemc.org</a></DIV>
<!-- </Donaciones to IMEMC obj id 2124> -->

<?php getPageLanguageOptions("ot", Array("0" => "en", "1" => "sp"), "2124"); ?>
         <?php
          global $editor_session, $pseudo_directory_offset;
          if(($editor_session->canEditLayout()|| $editor_session->canEditContent()) && ($editor_session->editor->allowedReadAccessTo("editdataobjects") || $editor_session->editor->allowedReadAccessTo("editobjdocument", 1)))
          {
          ?>
             <br>
            <a href="<?php echo $pseudo_directory_offset.$OSCAILT_SCRIPT ?>?obj_id=1&amp;obj_type=document&amp;target_id=2124&amp;action=edit&amp;site_id=1&amp;obj_language=ot&amp;edit_entry_url=[<?=$_REQUEST["obj_id"]?>][][][][][]"><img hspace=1 border=0  align="left" title="Edit Static Document [Donaciones to IMEMC] Configuration" alt="Edit Static Document [Donaciones to IMEMC] Configuration" src="<?php echo $pseudo_directory_offset?>graphics/mediaicons/32x32/editorial2.png" /></a>
             
          <?
          }
          ?>
          