

<!-- <left menu for article view obj id 2135> -->

         <?php
          global $editor_session, $graphics_store;
          if($editor_session->canEditLayout() && ($editor_session->editor->allowedReadAccessTo("editdataobjects") || $editor_session->editor->allowedReadAccessTo("editobjmenu", 1)))
          {
          ?>
             
            <a href="<?php echo $pseudo_directory_offset.$OSCAILT_SCRIPT ?>?obj_id=1&amp;obj_type=menu&amp;target_id=2135&amp;action=edit&amp;site_id=1&amp;obj_language=en&amp;edit_entry_url=[<?=$_REQUEST["obj_id"]?>][][][][][]"><img hspace=1 border=0 title="Edit Vertical Menu [left menu for article view] Configuration" alt="Edit Vertical Menu [left menu for article view] Configuration" src="<?php echo $graphics_store?>editmenu.gif" /></a>
             
          <?
          }
          ?>
       
         <?php
          global $editor_session, $graphics_store;
          if($editor_session->canEditLayout() && ($editor_session->editor->allowedReadAccessTo("editdataobjects") || $editor_session->editor->allowedReadAccessTo("editobjlist", 1)))
          {
          ?>
             
            <a href="<?php echo $pseudo_directory_offset.$OSCAILT_SCRIPT ?>?obj_id=1&amp;obj_type=list&amp;target_id=67&amp;action=edit&amp;site_id=1&amp;obj_language=en&amp;edit_entry_url=[<?=$_REQUEST["obj_id"]?>][][][][][]"><img hspace=1 border=0 title="Edit Listing Box [site navigation] Configuration" alt="Edit Listing Box [site navigation] Configuration" src="<?php echo $graphics_store?>editobject.gif" /></a>
             
          <?
          }
          ?>
       

<!-- <site navigation obj id 67> -->
<div class='main-menu'>
<P class='main-menu'>
         <?php
          global $editor_session, $graphics_store;
          if($editor_session->canEditLayout() && ($editor_session->editor->allowedReadAccessTo("editdataobjects") || $editor_session->editor->allowedReadAccessTo("editobjnewswire", 1)))
          {
          ?>
             
            <a href="<?php echo $pseudo_directory_offset.$OSCAILT_SCRIPT ?>?obj_id=1&amp;obj_type=newswire&amp;target_id=2126&amp;action=edit&amp;site_id=1&amp;obj_language=en&amp;edit_entry_url=[<?=$_REQUEST["obj_id"]?>][][][][][]"><img hspace=1 border=0 title="Edit Newswire Module [IMEMC News] Configuration" alt="Edit Newswire Module [IMEMC News] Configuration" src="<?php echo $graphics_store?>editobject.gif" /></a>
             
          <?
          }
          ?>
       

<!-- <IMEMC News obj id 2126> -->
<a href='<?php echo $pseudo_directory_offset.$OSCAILT_SCRIPT ?>?obj_id=2126' class='main-menu' title='Latest News Articles'>Latest News Articles</a>
<!-- </IMEMC News obj id 2126> -->

</P>
<P class='main-menu'>
         <?php
          global $editor_session, $graphics_store;
          if($editor_session->canEditLayout() && ($editor_session->editor->allowedReadAccessTo("editdataobjects") || $editor_session->editor->allowedReadAccessTo("editobjnewswire", 1)))
          {
          ?>
             
            <a href="<?php echo $pseudo_directory_offset.$OSCAILT_SCRIPT ?>?obj_id=1&amp;obj_type=newswire&amp;target_id=2128&amp;action=edit&amp;site_id=1&amp;obj_language=en&amp;edit_entry_url=[<?=$_REQUEST["obj_id"]?>][][][][][]"><img hspace=1 border=0 title="Edit Newswire Module [audio] Configuration" alt="Edit Newswire Module [audio] Configuration" src="<?php echo $graphics_store?>editobject.gif" /></a>
             
          <?
          }
          ?>
       

<!-- <audio obj id 2128> -->
<a href='<?php echo $pseudo_directory_offset.$OSCAILT_SCRIPT ?>?obj_id=2128' class='main-menu' title='Latest Audio'>Latest Audio</a>
<!-- </audio obj id 2128> -->

</P>
<P class='main-menu'>
         <?php
          global $editor_session, $graphics_store;
          if($editor_session->canEditLayout() && ($editor_session->editor->allowedReadAccessTo("editdataobjects") || $editor_session->editor->allowedReadAccessTo("editobjnewswire", 1)))
          {
          ?>
             
            <a href="<?php echo $pseudo_directory_offset.$OSCAILT_SCRIPT ?>?obj_id=1&amp;obj_type=newswire&amp;target_id=2123&amp;action=edit&amp;site_id=1&amp;obj_language=en&amp;edit_entry_url=[<?=$_REQUEST["obj_id"]?>][][][][][]"><img hspace=1 border=0 title="Edit Newswire Module [human interest] Configuration" alt="Edit Newswire Module [human interest] Configuration" src="<?php echo $graphics_store?>editobject.gif" /></a>
             
          <?
          }
          ?>
       

<!-- <human interest obj id 2123> -->
<a href='<?php echo $pseudo_directory_offset.$OSCAILT_SCRIPT ?>?obj_id=2123' class='main-menu' title='Human Interest'>Human Interest</a>
<!-- </human interest obj id 2123> -->

</P>
<P class='main-menu'>
         <?php
          global $editor_session, $graphics_store;
          if($editor_session->canEditLayout() && ($editor_session->editor->allowedReadAccessTo("editdataobjects") || $editor_session->editor->allowedReadAccessTo("editobjnewswire", 1)))
          {
          ?>
             
            <a href="<?php echo $pseudo_directory_offset.$OSCAILT_SCRIPT ?>?obj_id=1&amp;obj_type=newswire&amp;target_id=2118&amp;action=edit&amp;site_id=1&amp;obj_language=en&amp;edit_entry_url=[<?=$_REQUEST["obj_id"]?>][][][][][]"><img hspace=1 border=0 title="Edit Newswire Module [opinion/analysis] Configuration" alt="Edit Newswire Module [opinion/analysis] Configuration" src="<?php echo $graphics_store?>editobject.gif" /></a>
             
          <?
          }
          ?>
       

<!-- <opinion/analysis obj id 2118> -->
<a href='<?php echo $pseudo_directory_offset.$OSCAILT_SCRIPT ?>?obj_id=2118' class='main-menu' title='Opinion/Analysis'>Opinion/Analysis</a>
<!-- </opinion/analysis obj id 2118> -->

</P>
<P class='main-menu'>
         <?php
          global $editor_session, $graphics_store;
          if($editor_session->canEditLayout() && ($editor_session->editor->allowedReadAccessTo("editdataobjects") || $editor_session->editor->allowedReadAccessTo("editobjnewswire", 1)))
          {
          ?>
             
            <a href="<?php echo $pseudo_directory_offset.$OSCAILT_SCRIPT ?>?obj_id=1&amp;obj_type=newswire&amp;target_id=2143&amp;action=edit&amp;site_id=1&amp;obj_language=en&amp;edit_entry_url=[<?=$_REQUEST["obj_id"]?>][][][][][]"><img hspace=1 border=0 title="Edit Newswire Module [Interviews] Configuration" alt="Edit Newswire Module [Interviews] Configuration" src="<?php echo $graphics_store?>editobject.gif" /></a>
             
          <?
          }
          ?>
       

<!-- <Interviews obj id 2143> -->
<a href='<?php echo $pseudo_directory_offset.$OSCAILT_SCRIPT ?>?obj_id=2143' class='main-menu' title='Interviews'>Interviews</a>
<!-- </Interviews obj id 2143> -->

</P>
<P class='main-menu'>
         <?php
          global $editor_session, $graphics_store;
          if($editor_session->canEditLayout() && ($editor_session->editor->allowedReadAccessTo("editdataobjects") || $editor_session->editor->allowedReadAccessTo("editobjfeature", 1)))
          {
          ?>
             
            <a href="<?php echo $pseudo_directory_offset.$OSCAILT_SCRIPT ?>?obj_id=1&amp;obj_type=feature&amp;target_id=54&amp;action=edit&amp;site_id=1&amp;obj_language=en&amp;edit_entry_url=[<?=$_REQUEST["obj_id"]?>][][][][][]"><img hspace=1 border=0 title="Edit Featurewire Module [features] Configuration" alt="Edit Featurewire Module [features] Configuration" src="<?php echo $graphics_store?>editobject.gif" /></a>
             
          <?
          }
          ?>
       

<!-- <features obj id 54> -->
<a href='<?php echo $pseudo_directory_offset ?>features' class='main-menu' title='features'>features</a>
<!-- </features obj id 54> -->

</P>


</div>
<!-- </site navigation obj id 67> -->


         <?php
          global $editor_session, $graphics_store;
          if($editor_session->canEditLayout() && ($editor_session->editor->allowedReadAccessTo("editdataobjects") || $editor_session->editor->allowedReadAccessTo("editobjlist", 1)))
          {
          ?>
             
            <a href="<?php echo $pseudo_directory_offset.$OSCAILT_SCRIPT ?>?obj_id=1&amp;obj_type=list&amp;target_id=2100&amp;action=edit&amp;site_id=1&amp;obj_language=en&amp;edit_entry_url=[<?=$_REQUEST["obj_id"]?>][][][][][]"><img hspace=1 border=0 title="Edit Listing Box [Feeds] Configuration" alt="Edit Listing Box [Feeds] Configuration" src="<?php echo $graphics_store?>editobject.gif" /></a>
             
          <?
          }
          ?>
       

<!-- <Feeds obj id 2100> -->
<div class='<?php echo $page_style; ?>'>
<h4 class='<?php echo $page_style; ?>'><a href='<?php echo $pseudo_directory_offset ?>feeds' class='<?php echo $page_style; ?>'>Feeds</a></h4><UL class='<?php echo $page_style; ?>'>
<LI class='<?php echo $page_style; ?>'>
         <?php
          global $editor_session, $graphics_store;
          if($editor_session->canEditLayout() && ($editor_session->editor->allowedReadAccessTo("editdataobjects") || $editor_session->editor->allowedReadAccessTo("editobjlink", 1)))
          {
          ?>
             
            <a href="<?php echo $pseudo_directory_offset.$OSCAILT_SCRIPT ?>?obj_id=1&amp;obj_type=link&amp;target_id=2103&amp;action=edit&amp;site_id=1&amp;obj_language=en&amp;edit_entry_url=[<?=$_REQUEST["obj_id"]?>][][][][][]"><img hspace=1 border=0 title="Edit Simple Link [Atom Summaries Link] Configuration" alt="Edit Simple Link [Atom Summaries Link] Configuration" src="<?php echo $graphics_store?>editobject.gif" /></a>
             
          <?
          }
          ?>
       

<!-- <Atom Summaries Link obj id 2103> -->
<a href='http://www.imemc.org/atom.xml' class='<?php echo $page_style; ?>' title='An atom feed of article summaries'><img class='object-icon' alt='Atom Summaries Link' title='Atom Summaries Link' src='<?php global $pseudo_directory_offset; echo $pseudo_directory_offset ?>attachments/sites/site_1/atomsummariesbutton.png'></a>
<!-- </Atom Summaries Link obj id 2103> -->

</LI>
<LI class='<?php echo $page_style; ?>'>
         <?php
          global $editor_session, $graphics_store;
          if($editor_session->canEditLayout() && ($editor_session->editor->allowedReadAccessTo("editdataobjects") || $editor_session->editor->allowedReadAccessTo("editobjlink", 1)))
          {
          ?>
             
            <a href="<?php echo $pseudo_directory_offset.$OSCAILT_SCRIPT ?>?obj_id=1&amp;obj_type=link&amp;target_id=2104&amp;action=edit&amp;site_id=1&amp;obj_language=en&amp;edit_entry_url=[<?=$_REQUEST["obj_id"]?>][][][][][]"><img hspace=1 border=0 title="Edit Simple Link [Atom Full Posts Link] Configuration" alt="Edit Simple Link [Atom Full Posts Link] Configuration" src="<?php echo $graphics_store?>editobject.gif" /></a>
             
          <?
          }
          ?>
       

<!-- <Atom Full Posts Link obj id 2104> -->
<a href='<? echo $pseudo_directory_offset; ?>atomfullposts.xml' class='<?php echo $page_style; ?>' title='An Atom Feed of articles with full content'><img class='object-icon' alt='Atom Full Posts Link' title='Atom Full Posts Link' src='<?php global $pseudo_directory_offset; echo $pseudo_directory_offset ?>attachments/sites/site_1/atomfullpostsbutton.png'></a>
<!-- </Atom Full Posts Link obj id 2104> -->

</LI>
<LI class='<?php echo $page_style; ?>'>
         <?php
          global $editor_session, $graphics_store;
          if($editor_session->canEditLayout() && ($editor_session->editor->allowedReadAccessTo("editdataobjects") || $editor_session->editor->allowedReadAccessTo("editobjlink", 1)))
          {
          ?>
             
            <a href="<?php echo $pseudo_directory_offset.$OSCAILT_SCRIPT ?>?obj_id=1&amp;obj_type=link&amp;target_id=2101&amp;action=edit&amp;site_id=1&amp;obj_language=en&amp;edit_entry_url=[<?=$_REQUEST["obj_id"]?>][][][][][]"><img hspace=1 border=0 title="Edit Simple Link [RSS Summaries Link] Configuration" alt="Edit Simple Link [RSS Summaries Link] Configuration" src="<?php echo $graphics_store?>editobject.gif" /></a>
             
          <?
          }
          ?>
       

<!-- <RSS Summaries Link obj id 2101> -->
<a href='<? echo $pseudo_directory_offset; ?>rss.xml' class='<?php echo $page_style; ?>' title='An RSS feed of article summaries'><img class='object-icon' alt='RSS Summaries Link' title='RSS Summaries Link' src='<?php global $pseudo_directory_offset; echo $pseudo_directory_offset ?>attachments/sites/site_1/rsssummariesbutton.png'></a>
<!-- </RSS Summaries Link obj id 2101> -->

</LI>
<LI class='<?php echo $page_style; ?>'>
         <?php
          global $editor_session, $graphics_store;
          if($editor_session->canEditLayout() && ($editor_session->editor->allowedReadAccessTo("editdataobjects") || $editor_session->editor->allowedReadAccessTo("editobjlink", 1)))
          {
          ?>
             
            <a href="<?php echo $pseudo_directory_offset.$OSCAILT_SCRIPT ?>?obj_id=1&amp;obj_type=link&amp;target_id=2102&amp;action=edit&amp;site_id=1&amp;obj_language=en&amp;edit_entry_url=[<?=$_REQUEST["obj_id"]?>][][][][][]"><img hspace=1 border=0 title="Edit Simple Link [RSS Full Posts Link] Configuration" alt="Edit Simple Link [RSS Full Posts Link] Configuration" src="<?php echo $graphics_store?>editobject.gif" /></a>
             
          <?
          }
          ?>
       

<!-- <RSS Full Posts Link obj id 2102> -->
<a href='<? echo $pseudo_directory_offset; ?>rssfullposts.xml' class='<?php echo $page_style; ?>' title='A feed articles containing their full content'><img class='object-icon' alt='RSS Full Posts Link' title='RSS Full Posts Link' src='<?php global $pseudo_directory_offset; echo $pseudo_directory_offset ?>attachments/sites/site_1/rssfullpostsbutton.png'></a>
<!-- </RSS Full Posts Link obj id 2102> -->

</LI>
<LI class='<?php echo $page_style; ?>'>
         <?php
          global $editor_session, $graphics_store;
          if($editor_session->canEditLayout() && ($editor_session->editor->allowedReadAccessTo("editdataobjects") || $editor_session->editor->allowedReadAccessTo("editobjlink", 1)))
          {
          ?>
             
            <a href="<?php echo $pseudo_directory_offset.$OSCAILT_SCRIPT ?>?obj_id=1&amp;obj_type=link&amp;target_id=2105&amp;action=edit&amp;site_id=1&amp;obj_language=en&amp;edit_entry_url=[<?=$_REQUEST["obj_id"]?>][][][][][]"><img hspace=1 border=0 title="Edit Simple Link [Podcast Link] Configuration" alt="Edit Simple Link [Podcast Link] Configuration" src="<?php echo $graphics_store?>editobject.gif" /></a>
             
          <?
          }
          ?>
       

<!-- <Podcast Link obj id 2105> -->
<a href='<? echo $pseudo_directory_offset; ?>podcast.xml' class='<?php echo $page_style; ?>' title='A podcast of the sites audio and video content'><img class='object-icon' alt='Podcast Link' title='Podcast Link' src='<?php global $pseudo_directory_offset; echo $pseudo_directory_offset ?>attachments/sites/site_1/rsspodcastbutton.png'></a>
<!-- </Podcast Link obj id 2105> -->

</LI>
<LI class='<?php echo $page_style; ?>'>
         <?php
          global $editor_session, $graphics_store;
          if($editor_session->canEditLayout() && ($editor_session->editor->allowedReadAccessTo("editdataobjects") || $editor_session->editor->allowedReadAccessTo("editobjlink", 1)))
          {
          ?>
             
            <a href="<?php echo $pseudo_directory_offset.$OSCAILT_SCRIPT ?>?obj_id=1&amp;obj_type=link&amp;target_id=2106&amp;action=edit&amp;site_id=1&amp;obj_language=en&amp;edit_entry_url=[<?=$_REQUEST["obj_id"]?>][][][][][]"><img hspace=1 border=0 title="Edit Simple Link [iTunes Store Podcast Link] Configuration" alt="Edit Simple Link [iTunes Store Podcast Link] Configuration" src="<?php echo $graphics_store?>editobject.gif" /></a>
             
          <?
          }
          ?>
       

<!-- <iTunes Store Podcast Link obj id 2106> -->
<a href='itms://phobos.apple.com/WebObjects/MZStore.woa/wa/viewPodcast?id=120904798' class='<?php echo $page_style; ?>' title='A link to the sites podcast in the iTunes music store'><img class='object-icon' alt='iTunes Store Podcast Link' title='iTunes Store Podcast Link' src='<?php global $pseudo_directory_offset; echo $pseudo_directory_offset ?>attachments/sites/site_1/itunesbutton.gif'></a>
<!-- </iTunes Store Podcast Link obj id 2106> -->

</LI>
</UL>

</div>
<!-- </Feeds obj id 2100> -->


         <?php
          global $editor_session, $graphics_store;
          if($editor_session->canEditLayout() && ($editor_session->editor->allowedReadAccessTo("editdataobjects") || $editor_session->editor->allowedReadAccessTo("editobjpreferences", 1)))
          {
          ?>
             
            <a href="<?php echo $pseudo_directory_offset.$OSCAILT_SCRIPT ?>?obj_id=1&amp;obj_type=preferences&amp;target_id=2031&amp;action=edit&amp;site_id=1&amp;obj_language=en&amp;edit_entry_url=[<?=$_REQUEST["obj_id"]?>][][][][][]"><img hspace=1 border=0 title="Edit User Preferences [user preference box] Configuration" alt="Edit User Preferences [user preference box] Configuration" src="<?php echo $graphics_store?>editobject.gif" /></a>
             
          <?
          }
          ?>
       

<!-- <user preference box obj id 2031> -->
<div class='<?php echo $page_style; ?>'>
<?php require_once "objects/indyruntime/preferencesdisplay.inc";

         $site_module = new preferencesDisplay(2031);
         $site_module->setFilters(Array("*"), Array("20", "19", "18", "17", "16", "15", "14", "13", "12", "11", "10", "9", "8", "7", "6", "5", "4", "3", "2", "1"), Array("en"), Array("*"), Array(""));
         $object_display_settings = (Array("siteobject" => "1", "newswireobject" => "2126", "articleobject" => "53", "featureobject" => "54", "galleryobject" => "64", "searchobject" => "2212", "archiveobject" => "55", "contactobject" => "84", "commentsobject"=> "0", "publishobject" => "57", "eventsobject" => "58"));
         $site_module->setSiteSettings($object_display_settings);
      $site_module->setAdminOptions(Array("title" => "user preferences", "display" => "Menu", "hsize" => "4", "class" => "", "fontsizetext" => "text size", "languagetext" => "Language", "profiletext" => "Edit Your Profile", "logouttext" => "Logout", "normaltext" => "Normal", "alltext" => "Edit All", "contenttext" => "Edit Content", "sitebuildertext" => "Edit Layout", "editmodetext" => "Set Editor Mode >>", "allprefstext" => "All Preferences", "oscailthometext" => "make this your IMEMC front page", "admintext" => "Oscailt Administration", "userstatustext" => "", "showfontsize" => "false", "showlanguage" => "true", "showoscailthome" => "false", "showaddbookmark" => "false", "showallprefs" => "false", "showeditmode" => "false", "showlogout" => "true", "showprofile" => "false", "showuserstatus" => "false"));

$site_module->setUserOptions(array());

         $site_module->retrieveHeadlines();
       ?>
</div>
<!-- </user preference box obj id 2031> -->


         <?php
          global $editor_session, $graphics_store;
          if($editor_session->canEditLayout() && ($editor_session->editor->allowedReadAccessTo("editdataobjects") || $editor_session->editor->allowedReadAccessTo("editobjcodebox", 1)))
          {
          ?>
             
            <a href="<?php echo $pseudo_directory_offset.$OSCAILT_SCRIPT ?>?obj_id=1&amp;obj_type=codebox&amp;target_id=2218&amp;action=edit&amp;site_id=1&amp;obj_language=en&amp;edit_entry_url=[<?=$_REQUEST["obj_id"]?>][][][][][]"><img hspace=1 border=0 title="Edit Code Box [Facebook-Like] Configuration" alt="Edit Code Box [Facebook-Like] Configuration" src="<?php echo $graphics_store?>editobject.gif" /></a>
             
          <?
          }
          ?>
       

<!-- <Facebook-Like obj id 2218> -->
<div class='<?php echo $page_style; ?>'>
<script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script><fb:like-box href="http://www.facebook.com/home.php#!/pages/Imemc-News/193374364015118" width="150" height="100" show_faces="false" stream="false" header="false"></fb:like-box>

<script type="text/javascript" src="http://s.skimresources.com/js/10790X691627.skimlinks.js"></script>
</div>
<!-- </Facebook-Like obj id 2218> -->


<!-- </left menu for article view obj id 2135> -->

