

<!-- <Arabic obj id 2148> -->
<P class='<?php echo $page_style; ?>'><a href='<?php echo $pseudo_directory_offset; ?>attachments/pnn.htm?target=_blank' class='<?php echo $page_style; ?>'><img class='<?php echo $page_style; ?>-thumbnail' src='<?php
            $fname = getFilteredFile("attachments/", "arabic", true);
            echo getResizedImageURL("attachments/$fname", 0, 0, false, 0); ?>' alt='' title='' /></a></P>
<!-- </Arabic obj id 2148> -->

