<?php
/************************************************************************/
/* Oscailt                                                              */
/* Indepenent Media Centre Content Management System                    */
/* ==================================================================== */
/* Copyright (c)2003-2005 by Independent Media Centre Ireland           */
/* http://www.indymedia.ie                                              */
/* Development List: oscailt@lists.indymedia.org                        */
/* See contributions.txt for the list of contributors                   */
/*                                                                      */
/* This program is free software. You can redistribute it and/or modify */
/* it under the terms of the GNU General Public License as published by */
/* the Free Software Foundation. http://www.gnu.org/copyleft/gpl.html   */
/*                                                                      */
/* This program is distributed in the hope that it will be useful,      */
/* but WITHOUT ANY WARRANTY; without even the implied warranty of       */
/* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        */
/* GNU General Public License for more details.                         */
/************************************************************************/

require_once($path_prefix."objects/indyobjects/indyobject.inc");
require_once($path_prefix."objects/indyobjects/indyobjectset.inc");
require_once($path_prefix."objects/indyobjects/indyobjectstub.inc");
require_once($path_prefix."objects/indyobjects/indyobjectref.inc");
require_once($path_prefix."objects/indyobjects/indybasicobject.inc");
require_once($path_prefix."objects/indyobjects/indyitemset.inc");
require_once($path_prefix."objects/indyobjects/indydatatype.inc");
require_once($path_prefix."objects/indyobjects/indyobjectactionrequest.inc");
require_once($path_prefix."objects/indyobjects/indyobjectmanager.inc");
require_once($path_prefix.'objects/indyobjects/indysitemodule.inc');
require_once($path_prefix.'objects/indyobjects/indycontentobject.inc');
require_once($path_prefix.'objects/indyobjects/indyobjectnamecache.inc');
?>