<?php
/************************************************************************/
/* Oscailt                                                              */
/* Indepenent Media Centre Content Management System                    */
/* ==================================================================== */
/* Copyright (c)2003-2005 by Independent Media Centre Ireland           */
/* http://www.indymedia.ie                                              */
/* Development List: oscailt@lists.indymedia.org                        */
/* See contributions.txt for the list of contributors                   */
/*                                                                      */
/* This program is free software. You can redistribute it and/or modify */
/* it under the terms of the GNU General Public License as published by */
/* the Free Software Foundation. http://www.gnu.org/copyleft/gpl.html   */
/*                                                                      */
/* This program is distributed in the hope that it will be useful,      */
/* but WITHOUT ANY WARRANTY; without even the implied warranty of       */
/* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        */
/* GNU General Public License for more details.                         */
/************************************************************************/
?>
   <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/1999/REC-html401-19991224/loose.dtd">
   <HTML>
   <HEAD>
      <TITLE>
      <?=$pageTitle?> - No Page Layout Set
      </TITLE>
      <meta http-equiv=Content-Type content="text/html; charset=iso-8859-1">
      <meta name="description" content="<?=$pageDescription?>" />
      <meta name="keywords" content="<?= $pageKeywords ?>" />
      <link href="<?=$system_config->site_file_store_base?>default/style.css" type="text/css" rel="stylesheet">
      <link href="<?=$system_config->site_file_store_base?>default/common.css" type="text/css" rel="stylesheet">
   </HEAD>
   <BODY>
<?