<?php

//Constants to represent the context that objects find themselves in...
define ('FULL_DEPTH', 0);
define ('SUMMARY_DEPTH', 1);
define ('LONG_MENU_DEPTH', 2);
define ('SHORT_MENU_DEPTH', 3);
define ('LONG_LIST_DEPTH', 4);
define ('SHORT_LIST_DEPTH', 5);
define ('BAR_DEPTH', 6);

//Constants to represent the various types of messages
define ('USER_ERROR', 0);
define ('USER_WARNING', 1);
define ('USER_MSG', 2);
define ('INDY_ERROR', 3);
define ('INDY_WARNING', 4);
define ('INDY_MSG', 5);
define ('DEBUG_LEVEL_1', 6);
define ('DEBUG_LEVEL_2', 7);
define ('DEBUG_LEVEL_3', 8);

?>
