

<!-- <News Ticker obj id 2153> -->
<h1 class='<?php echo $page_style; ?>'>NEW on IMEMC</h1><BLOCKQUOTE class='<?php echo $page_style; ?>'></BLOCKQUOTE><DIV class='<?php echo $page_style; ?>'><object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"
 codebase="http://active.macromedia.com/flash4/cabs/swflash.cab#version=4,0,0,0"
 id="ticker" width="157" height="193">
 <param name="movie" value="http://www.imemc.org/graphics/ticker.swf">
 <param name="quality" value="high">
 <param name="bgcolor" value="#FFFFFF">
 <embed name="ticker" src="http://www.imemc.org/graphics/ticker.swf" quality="high" bgcolor="#FFFFFF"
 width="157" height="193"
 type="application/x-shockwave-flash"
 pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash">
 </embed>
</object></DIV>
<!-- </News Ticker obj id 2153> -->

