<?php global $pseudo_directory_offset; $site_file_store = $pseudo_directory_offset."attachments/sites/default/"; 
$oscailt_page_setting = Array("site_module_settings" => Array("siteobject" => "1", "newswireobject" => "2126", "articleobject" => "53", "featureobject" => "54", "galleryobject" => "64", "searchobject" => "2212", "archiveobject" => "55", "contactobject" => "84", "commentsobject" => "", "publishobject" => "57", "eventsobject" => "58"), "site_mail_settings" => Array("to" => "news@imemc.org", "from" => "site@imemc.org", "subject_prefix" => "Article edit:", "replyto" => "news@imemc.org", "level" => "none"), "site_filters" => Array("topic" => Array("0" => "*"), "region" => Array("0" => "20", "1" => "19", "2" => "18", "3" => "17", "4" => "16", "5" => "15", "6" => "14", "7" => "13", "8" => "12", "9" => "11", "10" => "10", "11" => "9", "12" => "8", "13" => "7", "14" => "6", "15" => "5", "16" => "4", "17" => "3", "18" => "2", "19" => "1"), "language" => Array("0" => "en"), "type" => Array("0" => "*"), "author" => ""), "obj_id" => "2193", "obj_type" => "DOCUMENT", "site_id" => "1");
$oscailt_story_query = new StoryQuery();
$oscailt_story_query->loadFormValues();
$PAGE_LAYOUT_ID = 60; ?>
<?
         addToPageDescription("The IMEMC is a media collective. We are independent journalists producing and distributing the authentic voices of the people.  We are located in Beit Sahour, in the Occupied West Bank, and we welcome new volunteers and contributors.");
      addToPageTitle("IMEMC Video Production Unit");
         addToPageDescription("Videos produced by IMEMC\'s VPU"); ?>

<!-- <IMEMC Video Production Unit obj id 2193> -->
<h1 class='indypagebody'>IMEMC Video</h1><BLOCKQUOTE class='indypagebody'>Below are videos produced by IMEMC Video Production Unti.
This is a fresh unit, it needs your support.</BLOCKQUOTE><DIV class='indypagebody'><p>IMEMC Video Production Unit is still not fully ready yet. We are trying to build it up step by step by producing some videos and saving little money to buy new equipment. However, we still lack lots of things. Despite that, the unit has produced a number of films with the simple equipment we have. Of course we had to rent some equipment when needed which lowers the benefit we can get from producing films.</p>

Check out the latest promotion clip produced for the Shepherds' Night's Festival
<center><object style="height: 390px; width: 640px"><param name="movie" value="http://www.youtube.com/v/T4Un76qaqac?version=3"><param name="allowFullScreen" value="true"><param name="allowScriptAccess" value="always"><embed src="http://www.youtube.com/v/T4Un76qaqac?version=3" type="application/x-shockwave-flash" allowfullscreen="true" allowScriptAccess="always" width="640" height="390"></object></center>

The first Seven Clips Produced by the unit<br /><br />
<b>Clip Number Seven</b><br />
A short documentary about Ush Ghrab site in Beit Sahour near Bethlehem in Palestine, which was an Israeli military base evacuated in 2006. Israeli settlers are trying to re-occupy the site, and Palestinian and international peace activists are trying to protect the land to allow space for a children hospital to be built on the site.<br /><br />
<center><object width="425" height="350"> <param name="movie" value="http://www.youtube.com/v/f9ZaFwi6WBo"> </param> <embed src="http://www.youtube.com/v/f9ZaFwi6WBo" type="application/x-shockwave-flash" width="425" height="350"> </embed> </object>
</center><br /><br />
<b>Clip Number Six:</b><br />
A short report about the Christmas celebrations in Bethlehem, December 24, 2007.
<center><object width="425" height="350"> <param name="movie" value="http://www.youtube.com/v/sONUbGT-8yI"> </param> <embed src="http://www.youtube.com/v/sONUbGT-8yI" type="application/x-shockwave-flash" width="425" height="350"> </embed> </object></center><br />

<b>Clip Number Five:</b><br />
Military occupation is very bad, but how about a privitized occupation, can there be a humane occupation?<br />
<center><object width="425" height="355"><param name="movie" value="http://www.youtube.com/v/p2UZirFNpDw&rel=1"></param><param name="wmode" value="transparent"></param><embed src="http://www.youtube.com/v/p2UZirFNpDw&rel=1" type="application/x-shockwave-flash" wmode="transparent" width="425" height="355"></embed></object></center><br />

<b>Clip Number Four:</b><br />
The word village is even huge for Tuwani, yet, the Israeli army and settlers apparently do not want it to exist in the first place.<br />
<center><object width="425" height="355"><param name="movie" value="http://www.youtube.com/v/NsesMjWkAl8&rel=1"></param><param name="wmode" value="transparent"></param><embed src="http://www.youtube.com/v/NsesMjWkAl8&rel=1" type="application/x-shockwave-flash" wmode="transparent" width="425" height="355"></embed></object></center><br />

<b>Clip Number Three:</b><br />
Building the wall in the village of Al_Walaja near Bethlehem, did not only strangle life in that village, but it has also created tention between the villagers and the priests of the nearby monastary, who have been neighbors for a very long time.<br />
<center>
<object width="425" height="355"><param name="movie" value="http://www.youtube.com/v/jLzjNfYM9XY&rel=1"></param><param name="wmode" value="transparent"></param><embed src="http://www.youtube.com/v/jLzjNfYM9XY&rel=1" type="application/x-shockwave-flash" wmode="transparent" width="425" height="355"></embed></object></center><br />

<b>Clip Number Two:</b><br />
Taybe Beer is the first and only Beer in Palestine. It is one of the successful
<p>
<center><object width="425" height="355"><param name="movie" value="http://www.youtube.com/v/nt0IWqBE0lY&rel=1"></param><param name="wmode" value="transparent"></param><embed src="http://www.youtube.com/v/nt0IWqBE0lY&rel=1" type="application/x-shockwave-flash" wmode="transparent" width="425" height="355"></embed></object></center></P>

<b>Clip Number One:</b><br />
Flashes from the second international conference on Nonviolence in Bilin, gives you the message of the conference.<br />
<center>
<embed style="width:400px; height:326px;" id="VideoPlayback" type="application/x-shockwave-flash" src="http://video.google.com/googleplayer.swf?docId=29781625495880441&hl=en" flashvars=""> </embed></center></DIV>
<!-- </IMEMC Video Production Unit obj id 2193> -->


         <?php
          global $editor_session, $pseudo_directory_offset;
          if(($editor_session->canEditLayout()|| $editor_session->canEditContent()) && ($editor_session->editor->allowedReadAccessTo("editdataobjects") || $editor_session->editor->allowedReadAccessTo("editobjdocument", 1)))
          {
          ?>
             <br>
            <a href="<?php echo $pseudo_directory_offset.$OSCAILT_SCRIPT ?>?obj_id=1&amp;obj_type=document&amp;target_id=2193&amp;action=edit&amp;site_id=1&amp;obj_language=en&amp;edit_entry_url=[<?=$_REQUEST["obj_id"]?>][][][][][]"><img hspace=1 border=0  align="left" title="Edit Static Document [IMEMC Video Production Unit] Configuration" alt="Edit Static Document [IMEMC Video Production Unit] Configuration" src="<?php echo $pseudo_directory_offset?>graphics/mediaicons/32x32/editorial2.png" /></a>
             
          <?
          }
          ?>
          