

<!-- <clock obj id 2195> -->
<script src="http://www.clocklink.com/embed.js"></script><script type="text/javascript" language="JavaScript">obj=new Object;obj.clockfile="5004p-orange.swf";obj.TimeZone="GMT0300";obj.width=130;obj.height=18;obj.Place="Jerusalem, Palestine";obj.DateFormat="yyyy / mm / dd DDD";obj.TimeFormat="HH:mm:ss TT";obj.wmode="transparent";showClock(obj);</script>
<!-- </clock obj id 2195> -->

