<?php global $pseudo_directory_offset; $site_file_store = $pseudo_directory_offset."attachments/sites/default/"; 
$oscailt_page_setting = Array("site_module_settings" => Array("siteobject" => "1", "newswireobject" => "2126", "articleobject" => "53", "featureobject" => "54", "galleryobject" => "64", "searchobject" => "2212", "archiveobject" => "55", "contactobject" => "84", "commentsobject" => "", "publishobject" => "57", "eventsobject" => "58"), "site_mail_settings" => Array("to" => "news@imemc.org", "from" => "site@imemc.org", "subject_prefix" => "Article edit:", "replyto" => "news@imemc.org", "level" => "none"), "site_filters" => Array("topic" => Array("0" => "*"), "region" => Array("0" => "20", "1" => "19", "2" => "18", "3" => "17", "4" => "16", "5" => "15", "6" => "14", "7" => "13", "8" => "12", "9" => "11", "10" => "10", "11" => "9", "12" => "8", "13" => "7", "14" => "6", "15" => "5", "16" => "4", "17" => "3", "18" => "2", "19" => "1"), "language" => Array("0" => "en"), "type" => Array("0" => "*"), "author" => ""), "obj_id" => "2196", "obj_type" => "DOCUMENT", "site_id" => "1");
$oscailt_story_query = new StoryQuery();
$oscailt_story_query->loadFormValues();
$PAGE_LAYOUT_ID = 2032; ?>
<?
         addToPageDescription("The IMEMC is a media collective. We are independent journalists producing and distributing the authentic voices of the people.  We are located in Beit Sahour, in the Occupied West Bank, and we welcome new volunteers and contributors.");
      addToPageTitle("Radio Free Palestine");
         addToPageDescription("A description of the IMEMC special Naqba broadcast 2008"); ?>

<!-- <Radio Free Palestine obj id 2196> -->
<h1 class='indypagebody'>18 hour radio broadcast on 60 years of Palestinian dispossession</h1><BLOCKQUOTE class='indypagebody'>On THURSDAY, MAY 15th, from Midnight until 6pm (EST), the International Middle East Media Center in Bethlehem (Palestine) participated in an historic international radio reflection of the Palestinian Nakba or catastrophe. This unprecedented 18-hour collaborative radio broadcast included the participation of CKUT 90.3fm
in Montreal (Quebec, Canada), CHRY 105.5fm in Toronto (Ontario, Canada),
and KBOO 90.7fm in Portland (Oregon, USA), and contributions from
Pacifica Radio and Democracy Now!</BLOCKQUOTE><DIV class='indypagebody'>The full archives are now available for download as MP3 files, hour by hour (or, if you prefer to download individual segments, click on the 'complete schedule' link below):<br>
<a href="http://www.ckut.ca/nakba_material/archives/nakba_2008-05-15_00h.mp3">Hour 1 (midnight to 1 am)</a><br>
<a href="http://www.ckut.ca/nakba_material/archives/nakba_2008-05-15_01h.mp3">Hour 2 (1 am - 2 am)</a><br>
<a href="http://www.ckut.ca/nakba_material/archives/nakba_2008-05-15_02h.mp3">Hour 3 (2 am - 3 am)</a><br>
<a href="http://www.ckut.ca/nakba_material/archives/nakba_2008-05-15_03h.mp3">Hour 4 (3 am - 4 am)</a><br>
<a href="http://www.ckut.ca/nakba_material/archives/nakba_2008-05-15_04h.mp3">Hour 5 (4 am - 5 am)</a><br>
<a href="http://www.ckut.ca/nakba_material/archives/nakba_2008-05-15_05h.mp3">Hour 6 (5 am - 6 am)</a><br>
<a href="http://www.ckut.ca/nakba_material/archives/nakba_2008-05-15_06h.mp3">Hour 7 (6 am - 7 am)</a><br>
<a href="http://www.ckut.ca/nakba_material/archives/nakba_2008-05-15_07h.mp3">Hour 8 (7 am - 8 am)</a><br>
<a href="http://www.ckut.ca/nakba_material/archives/nakba_2008-05-15_08h.mp3">Hour 9 (8 am - 9 am)</a><br>
<a href="http://www.ckut.ca/nakba_material/archives/nakba_2008-05-15_09h.mp3">Hour 10 (9 am - 10 am)</a><br>
<a href="http://www.ckut.ca/nakba_material/archives/nakba_2008-05-15_10h.mp3">Hour 11 (10 am - 11 am)</a><br>
<a href="http://www.ckut.ca/nakba_material/archives/nakba_2008-05-15_11h.mp3">Hour 12 (11 am - 12 pm)</a><br>
<a href="http://www.ckut.ca/nakba_material/archives/nakba_2008-05-15_12h.mp3">Hour 13 (12 pm - 1 pm)</a><br>
<a href="http://www.ckut.ca/nakba_material/archives/nakba_2008-05-15_13h.mp3">Hour 14 (1 pm - 2 pm)</a><br>
<a href="http://www.ckut.ca/nakba_material/archives/nakba_2008-05-15_14h.mp3">Hour 15 (2 pm - 3 pm)</a><br>
<a href="http://www.ckut.ca/nakba_material/archives/nakba_2008-05-15_15h.mp3">Hour 16 (3 pm - 4 pm)</a><br>
<a href="http://www.ckut.ca/nakba_material/archives/nakba_2008-05-15_16h.mp3">Hour 17 (4 pm - 5 pm)</a><br>
<a href="http://www.ckut.ca/nakba_material/archives/nakba_2008-05-15_17h.mp3">Hour 18 (5 pm - 6 pm)</a><br>

<br>
Description of Broadcast:<br><br>
Thursday, May 15th, 2008, commemorates 60 years of the Palestinian Nakba.
In 1948 eighty-five percent of the Palestinians living in the areas that
became the state of Israel became refugees. More than 500 Palestinian
villages were depopulated and later destroyed to prevent the return of the
refugees. Today there are a total of 7 million Palestinian refugees,
dispersed throughout the world - the largest and longest running refugee
problem yet unresolved.
<br><br>
60-years later, Israel continues to occupy and colonize Palestinian land
through the construction of Jewish only settlements and the Wall in the
West Bank. The Gaza Strip has been turned into one large prison. Israel
violates international law and commits ongoing war crimes and crimes
against humanity. And Palestinians abroad are the world's oldest refugee
population, making-up more than one fourth of all refugees.
<br><br>
The following Radio Stations have confirmed carrying the Nakba-60 Broadcast<br /><br />

<b>CANADA</b><br /><br />

1) CKDU Halifax, Nova Scotia <br />
2) CFUV 101.9fm Victoria, BC<br />
3) CHRY 105.5fm Toronto, Ontario<br />
4) CKUT 90.3fm Montreal, Quebec<br />
5) CFRC Kingston, Ontario<br />
6) CILU 102.7FM Thunderbay, ON<br /><br />

<b>UNITED STATES</b><br /><br />
1) KBOO Portland, Oregon<br />
2) WPFW Washington, DC<br />
3) WRNC in Ashland, WI<br /><br />

<b>United Kingdom</b><br /><br />

1) Radio Resonance, London<br /><br />

<a href="http://humanrightsmedia.org/nakba.html">Click here for complete schedule</a>
<br><br>
<a href="http://humanrightsmedia.org/posters/nakba.pdf">Poster for promotion (PDF)</a></DIV>
<!-- </Radio Free Palestine obj id 2196> -->


         <?php
          global $editor_session, $pseudo_directory_offset;
          if(($editor_session->canEditLayout()|| $editor_session->canEditContent()) && ($editor_session->editor->allowedReadAccessTo("editdataobjects") || $editor_session->editor->allowedReadAccessTo("editobjdocument", 1)))
          {
          ?>
             <br>
            <a href="<?php echo $pseudo_directory_offset.$OSCAILT_SCRIPT ?>?obj_id=1&amp;obj_type=document&amp;target_id=2196&amp;action=edit&amp;site_id=1&amp;obj_language=en&amp;edit_entry_url=[<?=$_REQUEST["obj_id"]?>][][][][][]"><img hspace=1 border=0  align="left" title="Edit Static Document [Radio Free Palestine] Configuration" alt="Edit Static Document [Radio Free Palestine] Configuration" src="<?php echo $pseudo_directory_offset?>graphics/mediaicons/32x32/editorial2.png" /></a>
             
          <?
          }
          ?>
          