

<!-- <Urgent appeal for funds obj id 2198> -->
<h1 class='<?php echo $page_style; ?>'>URGENT APPEAL FOR FUNDS!</h1><BLOCKQUOTE class='<?php echo $page_style; ?>'>The International Middle East Media Center will close unless we raise funds now.</BLOCKQUOTE><DIV class='<?php echo $page_style; ?>'><center><a href="https://co.clickandpledge.com/default.aspx?wid=17066" target="_blank">Click here to donate online via Click & Pledge</a><br />
Or use the Paypal Donation buttons on the left column<br />
Your HELP is essential to keep IMEMC ALIVE</center>
<hr></DIV>
<!-- </Urgent appeal for funds obj id 2198> -->

