

<!-- <Urgent appeal for funds-sp obj id 2198> -->
<h1 class='<?php echo $page_style; ?>'>PETICION URGENTE DE FONDOS!</h1><BLOCKQUOTE class='<?php echo $page_style; ?>'></BLOCKQUOTE><DIV class='<?php echo $page_style; ?>'><center><font color="red">El Centro Internacional de Medios de Comunicacion de Oriente Medio, (International Middle East Media Center) corre el peligro de cerrar a menos que consigamos los fondos necesarios inmediatamente. TU puedes ayudar a que el IMEMC siga adelante!</font><br /><a href="https://co.clickandpledge.com/default.aspx?wid=17066" target="_blank">Clica aquiÃ?Â­ para donar online via Click & Pledge</a><br />
O utiliza los botones de Donacion Paypal en la columna de la izquierda<br />
Tu AYUDA es esencial para mantener el IMEMC, VIVO</center>
<hr></DIV>
<!-- </Urgent appeal for funds-sp obj id 2198> -->

