

<!-- <Urgent appeal for funds obj id 2199> -->
<div class='<?php echo $page_style; ?>'>

         <?php
          global $editor_session, $graphics_store;
          if($editor_session->canEditLayout() && ($editor_session->editor->allowedReadAccessTo("editdataobjects") || $editor_session->editor->allowedReadAccessTo("editobjbox", 1)))
          {
          ?>
             
            <a href="<?php echo $pseudo_directory_offset.$OSCAILT_SCRIPT ?>?obj_id=1&amp;obj_type=box&amp;target_id=2199&amp;action=edit&amp;site_id=1&amp;obj_language=ot&amp;edit_entry_url=[<?=$_REQUEST["obj_id"]?>][][][][][]"><img hspace=1 border=0 title="Edit Inset Box [Urgent appeal for funds] Configuration" alt="Edit Inset Box [Urgent appeal for funds] Configuration" src="<?php echo $graphics_store?>editmenu.gif" /></a>
             
          <?
          }
          ?>
       
         <?php
          global $editor_session, $graphics_store;
          if($editor_session->canEditLayout() && ($editor_session->editor->allowedReadAccessTo("editdataobjects") || $editor_session->editor->allowedReadAccessTo("editobjdocument", 1)))
          {
          ?>
             
            <a href="<?php echo $pseudo_directory_offset.$OSCAILT_SCRIPT ?>?obj_id=1&amp;obj_type=document&amp;target_id=2198&amp;action=edit&amp;site_id=1&amp;obj_language=en&amp;edit_entry_url=[<?=$_REQUEST["obj_id"]?>][][][][][]"><img hspace=1 border=0 title="Edit Static Document [Urgent appeal for funds] Configuration" alt="Edit Static Document [Urgent appeal for funds] Configuration" src="<?php echo $graphics_store?>editobject.gif" /></a>
             
          <?
          }
          ?>
       

<!-- <Urgent appeal for funds obj id 2198> -->
<h4 class='center'>URGENT APPEAL FOR FUNDS!</h4><BLOCKQUOTE class='center'>The International Middle East Media Center will close unless we raise funds now.</BLOCKQUOTE><DIV class='center'><center><a href="https://co.clickandpledge.com/default.aspx?wid=17066" target="_blank">Click here to donate online via Click & Pledge</a><br />
Or use the Paypal Donation buttons on the left column<br />
Your HELP is essential to keep IMEMC ALIVE</center>
<hr></DIV>
<!-- </Urgent appeal for funds obj id 2198> -->


</div>
<!-- </Urgent appeal for funds obj id 2199> -->

