

<!-- <copyright notice obj id 1931> -->
<?php global $system_config; ?>© 2001-<?= strftime("%Y", time())?> <?= $system_config->site_long_name?>. Unless otherwise stated by the author, all content is free for non-commercial reuse, reprint, and rebroadcast, on the net and elsewhere. Opinions are those of the contributors and are not necessarily endorsed by <?= $system_config->site_long_name?>. 
<a href="disclaimer.php">Disclaimer</a> | <a href="privacy.php">Privacy</a>
<!-- </copyright notice obj id 1931> -->

