

<!-- <site-banner obj id 1932> -->
<P class='<?php echo $page_style; ?>'><a href='<?php echo $pseudo_directory_offset; ?>index.php' class='<?php echo $page_style; ?>'><img class='<?php echo $page_style; ?>-thumbnail' src='<?php echo getResizedImageURL("graphics/newheader_1.jpg", 0, 0, false, 0); ?>' alt='International Middle East Media Center' title='International Middle East Media Center' /></a></P>
<!-- </site-banner obj id 1932> -->

