

<!-- <Funding Request obj id 2208> -->
<center>
<b>
<!-- The International Middle East Media Center is running an URGENT online fundraising campaign.
<</b><br /><br />
<strong>Please SUPPORT the IMEMC</strong>-->
Your donation helps keep the IMEMC FREE and INDEPENDENT</b><br />
<br />
<a href="https://co.clickandpledge.com/sp/d1/default.aspx?wid=48434" target="_blank">Click here to donate</a>. <br />
<!---You can give a one-time donation, or a monthly deduction from your bank account.<br />--->
</center>
<!-- </Funding Request obj id 2208> -->

