<?php global $pseudo_directory_offset; $site_file_store = $pseudo_directory_offset."attachments/sites/default/"; 
$oscailt_page_setting = Array("site_module_settings" => Array("siteobject" => "1", "newswireobject" => "2126", "articleobject" => "53", "featureobject" => "54", "galleryobject" => "64", "searchobject" => "2212", "archiveobject" => "55", "contactobject" => "84", "commentsobject" => "", "publishobject" => "57", "eventsobject" => "58"), "site_mail_settings" => Array("to" => "news@imemc.org", "from" => "site@imemc.org", "subject_prefix" => "Article edit:", "replyto" => "news@imemc.org", "level" => "none"), "site_filters" => Array("topic" => Array("0" => "*"), "region" => Array("0" => "20", "1" => "19", "2" => "18", "3" => "17", "4" => "16", "5" => "15", "6" => "14", "7" => "13", "8" => "12", "9" => "11", "10" => "10", "11" => "9", "12" => "8", "13" => "7", "14" => "6", "15" => "5", "16" => "4", "17" => "3", "18" => "2", "19" => "1"), "language" => Array("0" => "en"), "type" => Array("0" => "*"), "author" => ""), "obj_id" => "2216", "obj_type" => "DOCUMENT", "site_id" => "1");
$oscailt_story_query = new StoryQuery();
$oscailt_story_query->loadFormValues();
$PAGE_LAYOUT_ID = 2032; ?>
<?
         addToPageDescription("The IMEMC is a media collective. We are independent journalists producing and distributing the authentic voices of the people.  We are located in Beit Sahour, in the Occupied West Bank, and we welcome new volunteers and contributors.");
      addToPageTitle("Radio Free Palestine 2010");
         addToPageDescription("Nakba 62 anniversary"); ?>

<!-- <Radio Free Palestine 2010 obj id 2216> -->
<h1 class='indypagebody'>Radio Free Palestine 2010</h1><BLOCKQUOTE class='indypagebody'>Radio Free Palestine is presented by the IMEMC (in Beit Sahour) and CKUT Radio (in Montreal) in commemoration of the 62nd anniversary of the Palestinian Nakba or catastrophe, marked this year on May 15th, 2010.</BLOCKQUOTE><DIV class='indypagebody'>In 1948 eighty-five percent of the Palestinians living in the areas that became the state of Israel became refugees. More than 500 Palestinian villages were depopulated and later destroyed to prevent the return of the refugees. Today there are a total of 7 million Palestinian refugees, dispersed throughout the world - the largest and longest running refugee problem yet unresolved.<br /><br />

62-years later, Israel continues to occupy and colonize Palestinian land through the construction of Jewish only settlements and the Wall in the West Bank. The Gaza Strip has been turned into one large prison. Israel violates international law and commits ongoing war crimes and crimes against humanity. And Palestinians abroad are the world's oldest refugee population, making-up more than one fourth of all refugees.<br /><br />

<b>WHEN? Thursday, May 13th, 2010</b><br /><br />

If your station wants to participate in this broadcast, confirm your interest in REBROADCASTING today, email <a mailto:"news@ckut.ca">news@ckut.ca</a>.

Air this promo and any of the content from this special broadcast, before or after the date.

MP3 Audio Promos (pls add your station's broadcast details):<br /><br />

http://previous.ncra.ca/business/admin_ncra/progex/prog...o.wav<br />
http://previous.ncra.ca/business/admin_ncra/progex/prog...o.wav<br /><br />

CKUT received the 2009 Community Radio Awards for Best Special Programming
for the Radio Free Palestine Broadcast held May 15th, 2008. The entirety of that broadcast is archived here: <a href="http://imemc.org/radio_free_palestine" target="_blank">http://imemc.org/radio_free_palestine</a>

Please contact Gretchen king (news@ckut.ca / 514.448.4041 x6788) with any
questions.<br /><br />

RADIO FREE PALESTINE REBROADCASTERS:<br />
CKUT Montreal, Quebec<br />
KBOO Portland, Oregon<br />
CFRU Guelph, Ontario<br />
CKDU, Halifax, Nova Scotia<br />
"Radio Intifada" (KPFK/Pacifica fm radio, Los Angeles, California)<br /><br />

<b>**Thursday, May 13th, tentative schedule**</b><br /><br />

Hours 7-9am will be in French.<br /><br />

:: 7am<br />
-Remembering the Nakba: Stories with community elders who were there<br />
-Commemoration on the life of Rezeq Faraj, 1943-2009<br /><br />

:: 8am<br />
-review of Regards Palestinian<br />
(http://regardspalestiniensmtl.blogspot.com/) with mary-ellen davis -Samir
Abdallah réalisateurs de documentaire Gaza-Strophes! Le Jour d'après<br />
-abdulrahman on Nakba commemorations in Djibouti<br />
-french music about Palestine<br /><br />

:: 9am<br />
-traditional music from Palestine<br />
-live with palestinian poet tamim barghoti performing later that night in
montreal<br />
-oral histories from people in Nablus who lived through the Nakba in
arabic with english translation<br /><br />

:: 10am<br />
-a special on Palestinian Christians 28 mins (Jenka)<br />
-one state with ali abunimah (sabine or excerpts from KBOO rec of Ali
lecture)<br /><br />

:: 11am<br />
-Media bias on the Palestine-Israel issue<br />
-Tawfiq Zayyad's poem, Here We Shall Stay<br />
-a long documentary about kids in Palestine<br /><br />

:: Noon<br />
Women's Music for Palestine<br /><br />

:: 1pm<br />
-Palestinian women under occupation (Samaa)<br />
-Susan Abulhawa about her novel, Mornings In Jenin.<br /><br />

:: 2pm<br />
-cultural commemorations of the Nakba<br />
-recordings from Palestinian Festival of Literature<br />

Break for 2 hours.<br /><br />

:: 5pm<br />
-Palestinian Prisoners<br />
-Kevin Neish, crew member, free Gaza boats<br />
-'Impressions of Palestine': conversations with Palestinians, Jews, and
Canadian activists on recent solidarity visits, study tours, and family
visits to the West Bank.<br /><br />

<b><center>CHECK THE ARCHIVED 2008 RFP: <a href="http://www.imemc.org/radio_free_palestine" target="_blank">http://www.imemc.org/radio_free_palestine</a></center></b></DIV>
<!-- </Radio Free Palestine 2010 obj id 2216> -->


         <?php
          global $editor_session, $pseudo_directory_offset;
          if(($editor_session->canEditLayout()|| $editor_session->canEditContent()) && ($editor_session->editor->allowedReadAccessTo("editdataobjects") || $editor_session->editor->allowedReadAccessTo("editobjdocument", 1)))
          {
          ?>
             <br>
            <a href="<?php echo $pseudo_directory_offset.$OSCAILT_SCRIPT ?>?obj_id=1&amp;obj_type=document&amp;target_id=2216&amp;action=edit&amp;site_id=1&amp;obj_language=en&amp;edit_entry_url=[<?=$_REQUEST["obj_id"]?>][][][][][]"><img hspace=1 border=0  align="left" title="Edit Static Document [Radio Free Palestine 2010] Configuration" alt="Edit Static Document [Radio Free Palestine 2010] Configuration" src="<?php echo $pseudo_directory_offset?>graphics/mediaicons/32x32/editorial2.png" /></a>
             
          <?
          }
          ?>
          