

<!-- <C&P-Meter obj id 2220> -->
<div id="ClimberAnimated" style="width: 150; height: 250; position: static;"></div><script src="https://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js" language="javascript"></script>
 <script type="text/javascript">
 swfobject.embedSWF("https://clickandpledge.s3.amazonaws.com/clickits/meters/005/r001/main.swf?destination=https://co.clickandpledge.com/default.aspx?wid=17066&message=Donate to help IMEMC News, we need $40,000&target=40000.00&accountID=12298&key=e64956ee-ff4f-4237-86e5-ae776ccb86b7&tracker=saveIMEMC", "ClimberAnimated", "150", "250", "10");
 </script>
<!-- </C&P-Meter obj id 2220> -->

