

<!-- <vertical-Ad obj id 2225> -->
<P class='<?php echo $page_style; ?>'><a href='<?php echo $pseudo_directory_offset; ?>mailto:"thepeacecycle@aol.com"' class='<?php echo $page_style; ?>'><img class='<?php echo $page_style; ?>-thumbnail' src='<?php echo getResizedImageURL("attachments/sites/site_1/tpc2013v.jpg", 400, 210, false, 0); ?>' alt='' title='' /></a></P>
<!-- </vertical-Ad obj id 2225> -->

