

<!-- <Donate - top bar obj id 2229> -->
<table width="100%">
<tr>
<td bgcolor=#DC143C align="center">
<p style="color:white;margin-left:20px;"><a style="color:#FFFFF0; font-size:large; font-weight:bold;text-decoration: none; align:center;" href="https://co.clickandpledge.com/sp/d1/default.aspx?wid=48434">Please help IMEMC continue to bring you news by donating now</a></p>
</td>
</tr>
</table>
<!-- </Donate - top bar obj id 2229> -->

