<?php global $pseudo_directory_offset; $site_file_store = $pseudo_directory_offset."attachments/sites/default/"; 
$oscailt_page_setting = Array("site_module_settings" => Array("siteobject" => "1", "newswireobject" => "2126", "articleobject" => "53", "featureobject" => "54", "galleryobject" => "64", "searchobject" => "2212", "archiveobject" => "55", "contactobject" => "84", "commentsobject" => "", "publishobject" => "57", "eventsobject" => "58"), "site_mail_settings" => Array("to" => "news@imemc.org", "from" => "site@imemc.org", "subject_prefix" => "Article edit:", "replyto" => "news@imemc.org", "level" => "none"), "site_filters" => Array("topic" => Array("0" => "*"), "region" => Array("0" => "20", "1" => "19", "2" => "18", "3" => "17", "4" => "16", "5" => "15", "6" => "14", "7" => "13", "8" => "12", "9" => "11", "10" => "10", "11" => "9", "12" => "8", "13" => "7", "14" => "6", "15" => "5", "16" => "4", "17" => "3", "18" => "2", "19" => "1"), "language" => Array("0" => "en"), "type" => Array("0" => "*"), "author" => ""), "obj_id" => "2233", "obj_type" => "DOCUMENT", "site_id" => "1");
$oscailt_story_query = new StoryQuery();
$oscailt_story_query->loadFormValues();
$PAGE_LAYOUT_ID = 1868; ?>
<?
         addToPageDescription("The IMEMC is a media collective. We are independent journalists producing and distributing the authentic voices of the people.  We are located in Beit Sahour, in the Occupied West Bank, and we welcome new volunteers and contributors.");
      addToPageTitle("List Of Gaza Casualties");
         addToPageDescription("List of casualties in Gaza since July 8th 2014"); ?>

<!-- <List of Gaza Casualties obj id 2233> -->
<h1 class='indypagebody'>List of Casualties in Gaza from 7/8 - 7/21</h1><BLOCKQUOTE class='indypagebody'><b>Last updated: 7/21/14 23:31 pm</b><br /><br />
At this time, the Palestinian Ministry of Health reports 578 killed. The names of 517 of these casualties have been confirmed, and are listed below.</BLOCKQUOTE><DIV class='indypagebody'>Of those killed, 129 are children and 69 are women, according to the Palestinian Center for Human Rights. The casualties listed below are victims of Israeli military attacks on Gaza since Tuesday July 8th. Israeli casualties follow, at the end of the list. <br />
<br />
<i>Killed Monday 7/21</i><br />
1. Shahinaz Walid Mohammad Abu Hamad, 1, Khan Younis.<br />
2. Husam Abu Qeinas, 5, Khan Younis.<br />
3. Somoud Nassr Siyam, 26, Gaza City.<br />
4. Bader Nabil Siyam, 25, Gaza City.<br />
5. Ahmad Ayman Mahrous Siyam, 17, Gaza City.<br />
6. Mustafa Nabil Mahrous Siyam, 12, Gaza City.<br />
7. Ghaidaâ?? Nabil Mahrous Siyam, 8, Gaza City.<br />
8. Dalal Nabil Mahrous Siyam, 8 months, Gaza City.<br />
9. Kamal Mahrous Salama Siyam, 27, Gaza City.<br />
10. Mohammad Mahrous Salaam Siyam, 25, Gaza City.<br />
11. Shireen Mahmoud Salaam Siyam, 32, Gaza City.<br />
12. Jowdat Tawfiq Ahmad Abu Jameâ??, 24, Khan Younis.<br />
13. Tawfiq Ahmad Abu Jameâ??, 5, Khan Younis.<br />
14. Haifa Tawfiq Ahmad Abu Jameâ??, 9, Khan Younis.<br />
15. Yasmin Ahmad Salama Abu Jameâ??, 25, Khan Younis.<br />
16. Soheila Bassam Abu Jameâ??, Khan Younis.<br />
17. Roseanne Tawfiq Ahmad Abu Jameâ??, 14, Khan Younis.<br />
18. Child from Abu Jameâ?? family, name not yet confirmed<br />
19. Child from Abu Jameâ?? family, name not yet confirmed.<br />
20. Woman from Abu Jameâ?? family, name not yet confirmed.<br />
21. Ahmad Suleiman Abu Saoud, 34, Khan Younis.<br />
22. Manwa Abdul-Baset as-Sabeâ??, 37, Beit Hanoun.<br />
23. Kamal Balal al-Masri, 22, Beit Hanoun.<br />
24. Bilal Jabr Mohammad al-Ashab, 22, Gaza City.<br />
25. Raed Ismail al-Bardawil, 26, Rafah.<br />
26. Zakariya Masoud al-Ashqar, 24, central Gaza.<br />
27. Abdullah Matroud Abu Hjeir, 16, central Gaza.<br />
28. Ahmad Salhoub, 34, central Gaza.<br />
29. Raed Issam Daoud, 30, Gaza City.<br />
30. Younis Ahmad Younis Sheikh al-Eid, 23, Rafah.<br />
31. Raja'e Hammad Mohammad, 38, Gaza.<br />
32. Ahmad Khale Daghmash, 21, Gaza.<br />
33. Mahmoud Hasan an-Nakhala, Gaza.<br />
34. Saleh Badawi, 31, Gaza.<br />
35. Kamal Masâ??oud, 21, Gaza.<br />
36. Mohammad Samih al-Ghalban, Gaza.<br />
37. Majdi Mahmoud al-Yazeji, 56, al-Karama, Gaza.<br /> 
38. Mayar al- Yazeji, 2, al-Karama, Gaza.<br />
39. Anas al- Yazeji, 5, al-Karama, Gaza.<br />
40. Yasmin Naif al-Yazeji, al-Karama, Gaza.<br />
41. Safinaz al-Yazeji, al-Karama, Gaza.<br />
42. Tamer Nayef Jundiyya, 30, Gaza.<br />
43. Kamel Jundiyya, 32, Gaza.<br />
44. Rahma Ahmad Jundiyya, 50.<br />
45. Mohammad Mahmoud al-Maghrebi, 24.<br />
46. Ibrahim Shaâ??ban Bakron, 37.<br />
47. Yousef Ghazi Hamdiyya, 25, Gaza.<br />
48. Moâ??taz Jamal Hamdiyya, 18, Gaza.<br />
49. â??Aaed Jamal Hamdiyya, 21. Gaza.<br />
50. Yasmin al-Qisas, Gaza City.<br />
51. Lamia Eyad al-Qisas, Gaza City.<br />
52. Nismaa Eyad al-Qisas, Gaza City.<br />
53. Arwa al-Qisas, Gaza City.<br />
54. Aya Yassr al-Qisas, Gaza City.<br />
55. Aishaâ?? Yassr al-Qisas, Gaza City.<br />
56. Aliya Siyam, Gaza City.<br />
57. Fayza Sabr Siyam, Gaza City.<br />
58. Samia Siyam, Gaza City.<br />
59. Fadi â??Azmi Buryam, Deir al-Balah.<br />
60. Ayman Salaam Buryam, Deir al-Balah.<br />
61. Salaam Abdul-Majeed Buryam, Deir al-Balah.<br />
62. Karim Ibrahim â??Atiya Barham, 25, Khan Younis.<br />
63. Nidal Ali Dakaâ??, 26, Khan Younis.<br />
64. Nidal Jamaaâ?? Abu â??Asy, 43, Khan Younis.<br />
65. Fatima Ahmad al-Arja, Rafah.<br />
66. Atiya Yusef Dardouna, 26, Jabalia.<br />
67. Mahmoud Shoeban Mohammad Derbas, 37, Gaza City.<br />
68. Ibrahim Deib Ahmad al-Kilani, 53 (father of Yassr and Elias) , Gaza City.<br />
69. Yassr Ibrahim Deib al-Kilani, 8, Gaza City.<br />
70. Elias Ibrahim Deib al-Kilani, 4, Gaza City.<br />
71. Susan Ibrahim Deib al-Kilani, 11, Gaza City.<br />
72. Reem Ibrahim Deib al-Kilani, 12, Gaza City.<br />
73. Taghrid Shoeban Mohammad al-Kilani, 45, Gaza City.<br />
74. Aidaâ?? Shoeban Mohammad Dirbas, 47, Gaza City.<br />
75. Fadi Bashir al-Ablala, 22, Khan Younis, Gaza City.<br />

<br />
<!---444 to this point--->
Killed Sunday 7/20<br />
1. Salem Ali Abu Sa'ada, Khan Younis.<br />
2. Mohammad Yusef Moammer, 30, Rafah.<br />
3. Hamza Yousef Moammer, 26, Rafah.<br />
4. Anas Yousef Moammar, 16.<br />
5. Hosni Mahmoud al-Absi, 56, Rafah.<br />
6. Suheib Ali Jomâ??a Abu Qoura, 21, Rafah.<br />
7. Ahmad Tawfiq Mohammad Zaâ??noun, 26, Rafah.<br />
8. Hamid Soboh Mohammad Fojo, 22, Rafah.<br />
9. Najah Saâ??ad al-Deen Daraji, 65, Rafah. <br />
10. Abdullah Yusef Daraji, 3, Rafah. <br />
11. Mohammed Raja'a Handam 15, Rafah.<br />
12. Yusef Shaâ??aban Ziada, 44, Al Bureij. <br />
13. Jamil Shaâ??aban Ziada, 53, Al Bureij. <br />
14. Shoeban Jamil Ziada, 12, Al Bureij (son of Jamil). <br />
15. Soheiib Abu Ziada, Al Bureij<br />
16. Mohammad Mahmoud al-Moqaddma, 30, Al Bureij.<br />
17. Raed Mansour Nayfa, Shujaâ??eyya (Gaza City). <br />
18. Fuad Jaber, Medic, Shujaâ??eyya (Gaza City). <br />
19. Mohammad Hani Mohammad al-Hallaq, 2, al-Rimal (Gaza City).<br />
20. Kenan Hasan Akram al-Hallaq, 6, al-Rimal - Gaza.<br />
21. Hani Mohammad al-Hallaq, 29, al-Rimal (Gaza City).<br />
22. Suad Mohammad al-Hallaq, 62, al-Rimal (Gaza City).<br />
23. Saje Hasan Akram al-Hallaq, 4, al-Rimal (Gaza City).<br />
24. Hala Akram Hasan al-Hallaq, 27, al-Rimal (Gaza City).<br />
25. Samar Osama al-Hallaq, 29, al-Rimal (Gaza City).<br />
26. Ahmad Yassin, al-Rimal (Gaza City).<br />
27. Ismael Yassin, al-Rimal (Gaza City)<br />
28. Aya Bahjat Abu Sultan, 15, Beit Lahia.<br />
29. Rayan Taysir Abu Jameâ??, 8, Khan Younis.<br />
30. Fatima Mahmoud Abu Jameâ??, 3, Khan Younis.<br />
31. Suleiman Abu Jameâ??, Khan Younis.<br />
32. Ibrahim Salem Jomâ??a as-Sahbani, 20, Shujaâ??eyya - Gaza.<br />
33. â??Aref Ibrahim al-Ghalyeeni, 26, Shujaâ??eyya - Gaza.<br />
34. Osama Khalil Ismael al-Hayya, 30, Shujaâ??eyya - Gaza. (father of Umama and Khalil)<br />
35. Hallah Saqer Hasan al-Hayya, 29, Shujaâ??eyya â?? Gaza. (mother of Umama and Khalil)<br /> 
36. Umama Osama Khalil al-Hayya, 9, Shujaâ??eyya - Gaza.<br />
37. Khalil Osama Khalil al-Hayya, 7, Shujaâ??eyya - Gaza.<br />
38. Rebhi Shehta â??Ayyad, 31, Shujaâ??eyya - Gaza.<br />
39. Yasser Ateyya Hamdiyya, 28, Shujaâ??eyya - Gaza.<br />
40. Esraâ?? Ateyya Hamdiyya, 28, Shujaâ??eyya - Gaza.<br />
41. Akram Mohammad Shkafy, 63, Shujaâ??eyya - Gaza.<br />
42. Eman Khalil Abed â??Ammar, 9, Shujaâ??eyya - Gaza.<br />
43. Ibrahim Khalil Abed Ammar, 13, Shujaâ??eyya - Gaza.*<br />
44. â??Asem Khalil Abed Ammar, 4, Shujaâ??eyya - Gaza.<br />
45. Eman Mohammad Ibrahim Hamada, 40, Shujaâ??eyya - Gaza.<br />
46. Ahmad Ishaq Yousef Ramlawy, 33, Shujaâ??eyya - Gaza.<br />
47. Ahmad Sami Diab â??Ayyad, 27, Shujaâ??eyya - Gaza.<br />
48. Fidaâ?? Rafiq Diab â??Ayyad, 24, Shujaâ??eyya - Gaza.<br />
49. Narmin Rafiw Diab Ayyad, 20, Shujaâ??eyya - Gaza.<br />
50. Ahmad Mohammad Ahmad Abu Zaâ??nouna, 28.<br /> 
51. Tala Akram Ahmad al-â??Atawy, 7, Shujaâ??eyya - Gaza.<br />
52. Tawfiq Barawi Salem Marshoud, 52, Shujaâ??eyya - Gaza.<br />
53. Hatem Ziad Ali Zaâ??bout, 24, Shujaâ??eyya - Gaza.<br />
54. Khaled Riyadh Mohammad Hamad, 25, Shujaâ??eyya - Gaza. (Journalist)<br />
55. Khadija Ali Mousa Shihada, 62, Shujaâ??eyya - Gaza.<br /> 
56. Khalil Salem Ibrahim Mosbeh, 53, Shujaâ??eyya - Gaza.<br />
57. â??Adel Abdullah Eslayyem, 2, Shujaâ??eyya - Gaza.<br />
58. Dina Roshdi Abdullah Eslayyem, 2, Shujaâ??eyya - Gaza.<br />
59. Rahaf Akram Ismael Abu Jomâ??a, 4, Shujaâ??eyya - Gaza.<br />
60. Shadi Ziad Hasan Eslayyem, 15, Shujaâ??eyya - Gaza.<br />
61. Ala Ziad Hasan Eslayyem, 11, Shujaâ??eyya - Gaza.<br />
62. Sherin Fathi Othman Ayyad, 18, Shujaâ??eyya - Gaza.<br />
63. â??Adel Abdullah Salem Eslayyem, 29, Shujaâ??eyya - Gaza.<br />
64. Fadi Ziad Hasan Eslayyem, 10, Shujaâ??eyya - Gaza.<br />
65. â??Ahed Saâ??ad Mousa Sarsak, 30, Shujaâ??eyya - Gaza.<br />
66. Aisha Ali Mahmoud Zayed, 54, Shujaâ??eyya - Gaza.<br />
67. Abed-Rabbo Ahmad Zayed, 58, Shujaâ??eyya - Gaza.<br />
68. Abdul-Rahman Akram Sheikh Khalil, 24, Shujaâ??eyya - Gaza.<br />
69. Mona Suleiman Ahmad Sheikh Khalil, 49.<br />
70. Heba Hamed Mohammad Sheikh Khalil, 13, Shujaâ??eyya - Gaza.<br />
71. Abdullah Mansour Radwan â??Amara, 23, Shujaâ??eyya - Gaza.<br />
72. Issam Atiyya Saâ??id Skafy, 26, Shujaâ??eyya - Gaza.<br />
73. Ali Mohammad Hasan Skafy, 27, Shujaâ??eyya - Gaza.<br />
74. Mohammad Hasan Skafy, 53, Shujaâ??eyya - Gaza.<br />
75. â??Ala Jamal ed-Deen Bardaâ??, 35, Shujaâ??eyya - Gaza.<br />
76. Omar Jamil Sobhi Hammouda, 10, Shujaâ??eyya - Gaza.<br />
77. Ghada Jamil Sobhi Hammouda, 10, Shujaâ??eyya - Gaza.<br />
78. Ghada Ibrahim Suleiman â??Adwan, 39, Shujaâ??eyya - Gaza.<br />
79. Fatima Abdul-Rahim Abu Ammouna, 55, Shujaâ??eyya - Gaza.<br />
80. Fahmi Abdul-Aziz Abu Saâ??id, 29, Shujaâ??eyya - Gaza.<br />
81. Ghada Sobhi Saâ??adi Ayyad, 9, Shujaâ??eyya - Gaza.<br />
82. Mohammad Ashraf Rafiq Ayyad, 6, Shujaâ??eyya - Gaza.<br />
83. Mohammad Raâ??ed Ehsan Ayyad, 6, Shujaâ??eyya - Gaza.<br />
84. Mohammad Rami Fathi â??Ayyad, 2, Shujaâ??eyya - Gaza.<br />
85. Mohammad Raâ??ed Ehsan â??Akeela, 19, Shujaâ??eyya - Gaza.<br />
86. Mohammad Ziad Ali Zaâ??bout, 23, Shujaâ??eyya - Gaza.<br />
87. Mohammad Ali Mohared Jundiyya, 38, Shujaâ??eyya - Gaza.<br />
88. Marah Shaker Ahmad al-Jammal, 2, Shujaâ??eyya - Gaza.<br />
89. Marwan Monir Saleh Qonfid, 23, Shujaâ??eyya - Gaza.<br />
90. Maisa Abdul-Rahman Sarsawy, 37, Shujaâ??eyya - Gaza.<br />
91. Marwa Salman Ahmad Sarsawy, 13, Shujaâ??eyya - Gaza.<br />
92. Mosâ??ab el-Kheir Salah ed-Din Skafi, 27, Shujaâ??eyya - Gaza.<br />
93. Mona Abdul-Rahman Ayyad, 42, Shujaâ??eyya - Gaza.<br />
94. Halla Sobhi Saâ??dy Ayyad, 25, Shujaâ??eyya - Gaza.<br />
95. Younis Ahmad Younis Mustafa, 62, Shujaâ??eyya - Gaza.<br />
96. Yousef Salem Hatmo Habib, 62, Shujaâ??eyya - Gaza.<br />
97. Fatima Abu Ammouna, 55, Shujaâ??eyya â?? Gaza.<br />
98. Ahmad Mohammad Azzam, 19, Shujaâ??eyya â?? Gaza.<br />
99. Ismael al-Kordi, Shujaâ??eyya â?? Gaza.<br />
<br />
<!--- 345 killed to this point--->
Killed Saturday 7/19<br />
<br />
1. Yahia Bassam as-Serry, 20, Khan Younis.<br />
2. Mohammad Bassam as-Serry, 17, Khan Younis.<br />
3. Mahmoud Rida Salhiyya, 56, Khan Younis.<br />
4. Mustafa Rida Salhiyya, 21, Khan Younis.<br />
5. Mohammad Mustafa Salhiyya, 22, Khan Younis.<br />
6. Waseem Rida Salhiyya, 15, Khan Younis.<br />
7. Ibrahim Jamal Kamal Nassr, 13, Khan Younis.<br />
8. Rushdi Khaled Nassr, 24, Khan Younis.<br />
9. Mohammad Awad Faris Nassr, 25, Khan Younis.<br />
10. Ahmad Mahmoud Hasan Aziz, 34, Beit Hanoun<br /> 
11. Saâ??id Ali Issa, 30, Juhr ed-Deek, Central Gaza.<br />
12. Raed Walid Laqan, 27, Khan Younis. <br />
13. Mohammad Jihad al-Qaraâ??, 29, Khan Younis.<br />
14. Rafat Ali Bahloul, 36, Khan Younis.<br />
15. Bilal Ismail Abu Doqqa, 33, Khan Younis.<br />
16. Mohammad Ismail Sammour, 21, Khan Younis.<br />
17. Eyad Ismael ar-Raqab, 26, Khan Younis.<br />
18. Mohammad Atallah Odah Saâ??adat, 25, Beit Hanoun.<br />
19. Mohammad Rafiq ar-Rohhal, 22, Beit Lahia.<br />
20. Mohammad Ziad ar-Rohhal, 6, Beit Lahia.<br />
21. Mohammad Ahmad Abu Zaâ??nouna, 37, Gaza City.<br />
22. Mahmoud Abdul-Hamid al-Zweidi, 23, Beit Lahia. <br />
23. Dalia Abdel-Hamid al-Zweidi, 37, Beit Lahia. <br />
24. Rowiya Mahmoud al-Zweidi, 6, Beit Lahia. <br />
25. Naghm Mahmoud al-Zweidi, 2, Beit Lahia. <br />
26. Mohammad Khaled Jamil al-Zweidi, 20, Beit Lahia. <br />
27. Amr Hamouda, 7, Beit Lahia. <br />
28. Mohammad Riziq Mohammad Hamouda, 18. <br />
29. Moâ??men Taysir al-â??Abed Abu Dan, 24, Central District. <br />
30. Abdul-Aziz Samir Abu Zaâ??itar, 31, Central District. <br />
31. Mohammad Ziad Zaâ??bout, 24, Gaza City. <br />
32. Hatem Ziad Zaâ??bout, 22, Gaza City. <br />
33. Fadal Mohammad al-Bana, 29, was killed in Jabalia. <br />
34. Mohammad Abdul-Rahman Abu Hamad, 25, Beit Lahia. <br />
35. Maâ??ali Abdul-Rahman Suleiman Abu Zeid, 24, Central District. <br />
36. Mohammad Ahmad as-Saidi, 18, Khan Younis. <br />
37. Abdul-Rahman Mohammad Odah, 23, Central District. <br />
38. Tariq Samir Khalil al-Hatou, 26, Central District. <br />
39. Mahmoud al-Sharif, 24, Central District. <br />
40. Mohammad Fathi al-Ghalban, 23, Khan Younis. <br />
41. Mahmoud Anwar Abu Shabab, 16, Rafah. <br />
42. Ahmad Abu Thurayya, 25, Central District. <br />
43. Abdullah Ghazi al-Masri, 30, Central District. <br />
44. Ayman Hisham an-Naâ??ouq, 25, Central District. <br />
45. Aqram Mahmoud al-Matouq, 37, Jabalia. <br />
<br />
<br />
<!--300 Killed To this Point-->
<br /> 
<i>Killed Friday 7/18</i><br />
<br />
1. Majdi Suleiman Jabara, 22, Rafah.<br />
2. Faris Jumaâ?? al-Mahmoum, 5 months, Rafah. <a href="http://www.imemc.org/article/68512">related article</a><br />
3. Omar â??Eid al-Mahmoum, 18, Rafah.<br />
4. Nassim Mahmoud Nassier, 22. Beit Hanoun.<br />
5. Karam Mahmoud Nassier, 20, Beit Hanoun.<br />
6. Salmiyya Suleiman Ghayyadh, 70, Rafah.<br />
7. Rani Saqer Abu Tawila, 30, Gaza City.<br />
8. Hammad Abdul-Karim Abu Lehya, 23, Khan Younis.<br />
9. Mohammad Abdul-Fattah Rashad Fayyad, 26, Khan Younis.<br />
10. Mahmoud Mohammad Fayyad, 25, Khan Younis.<br />
11. Amal Khader Ibrahim Dabbour, 40, Beit Hanoun<br />
12. Ismail Yousef Taha Qassim, 59, Beit Hanoun. <br />
13. Ahmad Fawzi Radwan, 23, Khan Younis. <br />
14. Mahmoud Fawzi Radwan, 24, Khan Younis.<br />
15. Bilal Mahmoud Radwan, 23, Khan Younis. <br />
16. Monther Radwan, 22, Khan Younis. <br />
17. Hani As'ad Abdul-Karim Shami, 35, Khan Younis.<br />
18. Mohammad Hamdan Abdul-Karim Shami, 35, Khan Younis.<br />
19. Husam Musallam Abu Issa, 26. Gaza. <br />
20. Ahmad Ismael Abu Musallam, 14, Gaza City. <br />
21. Mohammad Ismael Abu Musallam, 15, Gaza City. <br />
22. Walaâ?? Ismael Abu Musallam, 13, Gaza City. <br />
23. Naim Mousa Abu Jarad, 23, Beit Hanoun. <br />
24. Abed Mousa Abu Jarad, 30, Beit Hanoun. <br />
25. Siham Mousa Abu Jarad, 26, Beit Hanoun. <br />
26. Rajaâ?? Oliyyan Abu Jarad, 31, Beit Hanoun.<br />
27. Haniyya Abdul-Rahman Abu Jarad, 3, Beit Hanoun.<br />
28. Samih Naim Abu Jarad, 1, Beit Hanoun. <br />
29. Mousa Abul-Rahman Abu Jarad, 6 months, Beit Hanoun.<br />
30. Ahlam Mousa Abu Jarad, 13, Beit Hanoun.<br /> 
31. Husam Musallam Abu Aisha, 26, Jahr al-Deek.<br />
32. . Mohammad Saâ??ad Mahmoud Abu Saâ??da , Khan Younis.<br />
33. Raâ??fat Mohammad al-Bahloul, 35, Khan Younis.<br />
34. Walaâ?? al-Qarra, 20, Khan Younis.<br />
35. Abdullah Jamal as-Smeiri, 17, Khan Younis.<br />
36. Ahmad Hasan Saleh al-Ghalban, 23, Khan Younis.<br />
37. Hamada Abdullah Mohammad al-Bashiti, 21, Khan Younis.<br />
38. Hamza Mohammad Abu Hussein, 27, Rafah.<br />
39. Alaâ?? Abu Shabab, 23, Rafah.<br />
40. Mohammad â??Awad Matar, 37, Rafah.<br />
41. Bassem Mohammad Mahmoud Madhi, 22, Rafah.<br />
42. Ahmad Abdullah al-Bahnasawi, 25. Um An-Nasr.<br />
43. Saleh â??Zgheidy, 20, Rafah.<br />
44. Mahmoud Ali Darwish, 40, Nusseirat, Central Gaza.<br />
45. Yousef Ibrahim al-Astal, 23,Khan Younis.<!â??not on health ministry list but on family list--> <br />
46. Imad Hamed Eâ??lawwan, 7, Gaza.<br />
47. Qassem Hamed Eâ??lawwan, 4, Gaza (brother of Imad)><br />
48. Sarah Mohammad Bustan, 13, Gaza.<br />
49. Rezeq Ahmad al-Hayek, 2, Gaza.<br /> 
50. Mustafa Faisal Abu Sneina, 32, Rafah.<br />
51. Imad Faisal Abu Sneina, 18, Rafah.<br /> 
52. Nizar Fayez Abu Sneina, 38, Rafah.<br />
53. Ismail Ramadan al-Loulahi, 21, Khan Younis<br />
54. Ghassan Salem Mousa Abu â??Azab, 28, Khan Younis.<br />
55. Ahmad Salem Shaâ??at, 22, Khan Younis.<br />
56. Mohammad Salem Shaâ??at, 20, Khan Younis<br />
57. Amjad Salem Shaâ??at, 15, Khan Younis.<br />
58. Mohammad Talal as-Saneâ??, 20, Rafah.<br />
<br />
<br /><!---242 to this point--->
<i>KIlled Thursday 7/17</i><br />
<br />
1. Mohammad Mahmoud Al-Qadim, 22, Deir al-Balah.<br />
2. Mohammad Abdul-Rahman Hassouna, 67, Rafah.<br />
3. Zeinab Mohammad Saâ??id al-â??Abadla, 71, Khan Younis.<br />
4. Ahmad Reehan, 23, Beit Lahia.<br />
5. Salem Saleh Fayyad, 25, Gaza City.<br />
6. Abdullah Salem al-Atras, 27, Rafah.<br />
7. Bashir Mohammad Abdul-'Al, 20, Rafah.<br />
8. Mohammad Ziyad Ghanem, 25, Rafah.<br />
9. Mohammad Ahmad al-Hout, 41, Rafah.<br />
10. Fulla Tariq Shuhaibar, 8, Gaza City. <a href="http://www.imemc.org/article/68505">related article</a><br />
11. Jihad Issam Shuhaibar, 10, Gaza City.<a href="http://www.imemc.org/article/68505">related article</a><br />
12. Wasim Issam Shuhaibar, 9, Gaza City.<a href="http://www.imemc.org/article/68505">related article</a><br />
13. Rahaf Khalil al-Jbour, 4, Khan Younis. <a href="http://www.imemc.org/article/68505">related article</a><br />
14. Yassin al-Humaidi, 4, Gaza City (died of earlier wounds). <a href="http://www.imemc.org/article/68505">related article</a><br />
15. Ismail Youssef al-Kafarneh, Beit Hanoun. <br />
16. Hamza Hussein al-'Abadala, 29, Khan Younis. <br />
17. Abed Ali Ntheir, 26, Gaza City. <br />
18. Mohammad Shadi Ntheir, 15, Gaza City. <a href="http://www.imemc.org/article/68505">related article</a><br />
19. Mohammad Salem Ntheir, 4, Gaza City. <a href="http://www.imemc.org/article/68505">related article</a><br />
20. Salah Saleh ash-Shafeâ??ey, Khan Younis.<br />
<br />
<!--- 222 to this point --->
<i>Killed Wednesday 7/16</i><br />
<br />
1. Mohammad Ismael Abu Odah, 27, Rafah.<br />
2. Mohammad Abdullah Zahouq, 23, Rafah.<br />
3. Ahmed Adel Nawajha, 23, Rafah.<br />
4. Mohammad Taisir Abu Sharab, 23, Khan Younis.<br />
5. Mohammad Sabri ad-Debari, Rafah.<br />
6. Farid Mahmoud Abu-Doqqa, 33, Khan Younis.<br />
7. Ashraf Khalil Abu Shanab, 33, Rafah.<br />
8. Khadra Al-Abed Salama Abu Doqqa, 65, Khan Younis.<a href="http://www.imemc.org/article/68491">related article</a><br />
9. Omar Ramadan Abu Doqqa, 24, Khan Younis.<a href="http://www.imemc.org/article/68491">related article</a><br />
10. Ibrahim Ramadan Abu Doqqa, 10, Khan Younis.<a href="http://www.imemc.org/article/68491">related article</a><br />
11. Ahed Atef Bakr, 10, Gaza beach.<a href="http://www.imemc.org/article/68492">related article</a><br />
12. Zakariya Ahed Bakr, 10, Gaza beach.<a href="http://www.imemc.org/article/68492">related article</a><br /> 
13. Mohammad Ramiz Bakr, 11, Gaza beach.<a href="http://www.imemc.org/article/68492">related article</a><br /> 
14. Ismail Mahmoud Bakr, 9, Gaza beach. <a href="http://www.imemc.org/article/68492">related article</a><br /> 
15. Mohammad Kamel Abdul-Rahman, 30, Sheikh 'Ejleen, Gaza City.<br />
16.Husam Shamlakh, 23, Sheikh 'Ejleen, Gaza City. <br />
17.Usama Mahmoud Al-Astal, 6, Khan Younis. (died of wounds sustained earlier in attack on mosque)<br />
18. Hussein Abdul-Nasser al-Astal, 23, Khan Younis.<br />
19. Kawthar al-Astal, 70, Khan Younis.<br />
20. Yasmin al-Astal, 4, Khan Younis.<br />
21. Kamal Mohammad Abu 'Amer, 38, Khan Younis.<br />
22.Akram Mohammad Abu 'Amer, 34, Khan Younis. (brother of Kamal, injured in same incident, then later same day died of his injuries)<br />
23. Hamza Raed Thary, 6, Jabalia (was injured a few days ago in the incident in which many, including children, were killed while playing in the sand at the beach in Jabalia)<br />
24. Abdul-Rahman Ibrahim Khalil as-Sarhi, 37, Gaza City. <br />
<br />
<!---198 to this point---><br />
<br />
<i>Killed Tuesday 7/15:</i><br />
1. Abdullah Mohammad al-â??Arjani, 19, Khan Younis.<br />
2. Suleiman Abu Louly, 33, Rafah.<br />
3. Saleh Saâ??id Dahleez, 20, Rafah.<br />
4. Yasser Eid al-Mahmoum, 18, Rafah.<br />
5. Ismael Fattouh Ismael, 24, Gaza City. <br />
6. Khalil Shâ??aafy, Juhr Ed-Deek â?? Gaza.<br />
7. Sobhi Abdul-hamid Mousa, 77, Khan Younis.<br />
<br />
<i>Killed Monday 7/14:</i><br />
<br />
1. Adham Abdul-Fattah Abdul-â??Aal, 27<br />
2. Hamid Suleiman Abu al-â??Araj, 60, Deir al-Balah.<br />
3. Abdullah Mahmoud Baraka, 24, Khan Younis. <br />
4. Tamer Salem Qdeih, 37, Khan Younis. <br />
5. Ziad Maher an-Najjar, 17, Khan Younis. <br />
6. Ziad Salem ash-Shawy, 25, Rafah. <br />
7. Mohammad Yasser Hamdan, 24, Gaza. <br />
8. Mohammad Shakib al-Agha, 22, Khan Younis.<br /> 
9. Ahmed Younis Abu Yousef, 22, Khan Younis.<br />
<!---Mohammad Younis Abu Yousef, 28, Khan Younis.<br />--> 
10. Sara Omar Sheikh al-Eid, 4, Rafah.<br /> 
11. Omar Ahmad Sheikh al-Eid, 24, Rafah. <br />
12. Jihad Ahmad Sheikh al-Eid, 48, Rafah. <br />
13. Kamal Atef Yousef Abu Taha, 16, Khan Younis. <br />
14. Ismael Nabil Ahmad Abu Hatab, 21, Khan Younis. <br />
15. Boshra Khalil Zo'rob, 53, Rafah.<br />
16. Atwa 'Amira al-'Amour, 63, Khan Younis<br />
<br />
<i>Killed Sunday: 7/13</i><br />
<br />
1. Ezzeddin Bolbol, 25, Rafah.<br />
2. Rami Abu Shanab, 25, Deir al-Balah.<br />
3. Fawziyya Abdul-al, 73, Gaza City.<br />
4. Moâ??ayyad al-â??Araj, 3, Khan Younis.*<br />
5. Husam Ibrahim Najjar, 14, Jabalia.<br />
6. Hijaziyya Hamed al-Hilo, 80, Gaza City.<br />
7. Ruwaida abu Harb Zawayda, 30, central Gaza.<br />
8. Haitham Ashraf Zoâ??rob, 21, Rafah.<br />
9. Laila Hassan al-â??Odaat, 41, al-Maghazi.<br />
10. Hussein Abdul-Qader Mheisin, 19, Gaza.<br />
11. Qassem Talal Hamdan, 23, Beit Hanoun.<br />
12. Maher Thabet abu Mour, 23, Khan YounisÂ -Â <a href="http://www.imemc.org/article/68463">related article</a><br />
13. Mohammad Salem Abu Breis, 65, Deir al-Balah<br />
14. Moussa Shehda Moammer, 60, Khan Younis.<br />
15. Hanadi Hamdi Moammer, 27, Khan Younis.<br />
16. Saddam Mousa Moammer, 23, Khan Younis.<br />
<br />
<i>Killed Saturday 7/12</i><br />
<br />
1. Anas Yousef Qandil, 17, Jabalia.<br />
2. Islam Yousef Mohammad Qandil, 27, Jabalia.<br />
3. Mohammad Edrees Abu Sneina, 20, Jabalia.<br />
4. Abdul-Rahim Saleh al-Khatib, 38, Jabalia.<br />
5. Husam Thieb ar-Razayna, 39, Jabalia.<br />
6. Ibrahim Nabil Hamada, 30, at-Tuffah - Gaza City.<br />
7. Hasan Ahmad Abu Ghush, 24, at-Tuffah - Gaza City.<br />
8. Ahmad Mahmoud al-Balâ??awy, 26, at-Tuffah - Gaza City.<br />
9. Ali Nabil Basal, 32, at-Tuffah - Gaza City.<br />
10. Mohammad Bassem al-Halaby, 28, western Gaza City.<br />
11. Mohammad Sweity (Abu Askar), 20, western Gaza City.<br />
12. Khawla al-Hawajri, 25, Nuseirat refugee camp.<br />
13. Ola Wishahi, 31, Mabarra association for the disabled in Jabalia.<br />
14. Suha Abu Saade, 38, Mabarra association for the disabled in Jabalia.<br />
15. Mohammad Edrees Abu Sweilem, 20, Jabalia<br />
16. Rateb Subhi al-Saifi, 22, Sheikh Radwan â?? Gaza City. <br />
17. Azmi Mahmoud Obeid, 51, Sheikh Radwan â?? Gaza City. <br />
18. Nidal Mahmoud Abu al-Malsh, 22, Sheikh Radwan â?? Gaza City.<br />
19. Suleiman Said Obeid, 56, Sheikh Radwan â?? Gaza City. <br />
20. Mustafa Muhammad Inaya, 58, Sheikh Radwan â?? Gaza City. <br />
21. Ghassan Ahmad al-Masri, 25, Sheikh Radwan â?? Gaza City. <br /> 
22. Rifâ??at Youssef Amer, 36, al-Saftawi. <br />
23. Rifâ??at Syouti, western Gaza City.* <br />
24. Nahedh Naâ??im al-Batsh, 41, Khan Younis.<br />
25. Bahaâ?? Majed al-Batsh, 28, Khan Younis.<br />
26. Qusai Issam al-Batsh, 12, Khan Younis.<br />
27. Aziza Yousef al-Batsh, 59, Khan Younis.<br />
28. Ahmad Noâ??man al-Batsh, 27, Khan Younis.<br />
29. Mohammad Issam al-Batsh, 17, Khan Younis.<br />
30. Yahia â??Alaâ?? Al-Batsh, 18, Khan Younis.<br />
31. Jalal Majed al-Batsh, 26, Khan Younis.<br />
32. Mahmoud Majed al-Batsh, 22, Khan Younis<br />
33. Majed Sobhi al-Batsh, Khan Younis.<br />
34. Marwa Majed al-Batsh, 25, Khan Younis.<br />
35. Khaled Majed al-Batsh, 20, Khan Younis.<br />
36. Ibrahim Majed al-Batsh, 18, Khan Younis.<br />
37. Manar Majed al-Batsh, 13, Khan Younis.<br />
38. Amal Hussein al-Batsh, 49, Khan Younis.<br />
39. Anas Alaâ?? al-Batsh, 10, Khan Younis.<br />
40. Qusai Alaâ?? al-Batsh, 20, Khan Younis.<br />
41. Mohannad Yousef Dheir, 23, Rafah.<br />
42. Shadi Mohammad Zoâ??rob, 21, Rafah.<br />
43. Imad Bassam Zoâ??rob, 21, Rafah. <br />
44. Mohannad Yousef Dheir, 23, Rafah.<br />
45. Mohammad Arif, 13, eastern Gaza City.<br />
46. Mohammad Ghazi â??Arif, 35, eastern Gaza City. <br />
47. Ghazi Mustafa Arif, 62, eastern Gaza City. <br /> 
48. Ahmad Yousef Dalloul, 47, Gaza.<br />
49. Fadi Yaâ??coub Sukkar, 25, Gaza.<br />
50. Qassem Jaber Odah, 16, Khan Younis.<br /> 
51. Mohammad Abdullah Sharatha, 53, Jabalia.<br />
52. Mohammad Ahmed Basal, 19, Gaza City.<br />
<br />
<i>Killed Friday 7/11</i><br />
<br />
1. Wisam Abdul-Razeq Hasan Ghannam, 31, Rafah.<br />
2. Mahmoud Abdul-Razeq Hasan Ghannam, 28, Rafah.<br />
3. Kifah Shaker Ghannam, 33, Rafah.<br />
4. Ghalia Thieb Ghannam, 57, Rafah.<br />
5. Mohammad Munir â??Ashour, 26, Rafah.<br />
6. Nour Marwan an-Ajdi, 10, Rafah.<br />
7. Anas Rezeq abu al-Kas, 33, Gaza City (doctor).<br />
8. Abdullah Mustafa abu Mahrouq, 22, Deir al-Balah.<br />
9. Mahmoud Waloud, 26, Jabalia<br />
10. Hazem Baâ??lousha, Jabalia.<br />
11. Ala' Abdul Nabi, Beit Lahia.*<br />
12. Ahmed Zaher Hamdan, 24, Beit Hanoun.<br />
13. Mohammad Kamel al-Kahlout, 25, Jabalia.<br />
14. Sami Adnan Shaldan, 25, Gaza City<br />
15. Salem al-Ashhab, 40, Gaza City.<br /> 
16. Raed Hani Abu Hani, 31, Rafah.<br />
17. Mohammad Rabea Abu- Hmeedan, 65, Jabalia.<br />
18. Shahrman Ismail Abu al-Kas, 42, Al-Bureij.<br />
19. Mazin Mustafa Aslan, 63, Al Bureij.<br />
20. Mohammad Samiri, 24, Deir al-Balah. <br />
21. Rami Abu Mosaâ??ed, 23, Deir al-Balah. <br />
22. Saber Sokkar, 80, Gaza City. <br />
23. Hussein Mohammad al-Mamlouk, 47, Gaza City. <br />
24. Nasser Rabah Mohammad Sammama, 49, Gaza City. <br />
25. Abdul-Halim Abdul-Moâ??ty Ashra, 54, Deir al-Balah. <br />
26. Sahar Salman Abu Namous, 3, Beit Hanoun. <br />
27. Odai Rafiq Sultan, 27, Jabalia.<br />
28. Jomâ??a Atiyya Shallouf, 25, Rafah.<br />
29. Bassam Abul-Rahman Khattab, 6, Deir al-Balah<br />
<br>
<i>Killed Thursday 7/10:</i><br /><br />
1. Mahmoud Lutfi al-Hajj, 58, Khan Younis. (father of six killed)<br />
2. Bassema Abdul-fatteh Mohammad al-Hajj, 48, Khan Younis. (mother of six killed)<br />
3. Asmaâ?? Mahmoud al-Hajj, 22, Khan Younis.<br />
4. Fatima Mahmoud al-Hajj, 12, Khan Younis<br />
5. Saâ??ad Mahmoud al-Hajj, 17, Khan Younis.<br />
6. Najlaâ?? Mahmoud al-Hajj, 29, Khan Younis.<br />
7. Tareq Mahmoud al-Hajj, 18, Khan Younis.<br />
8. Omar Mahmoud al-Hajj, 20, Khan Younis.<br />
9. Bahaâ?? Abu al-Leil, 35, Gaza City.<br />
10. Suleiman Saleem Mousa al-Astal, 17, Khan Younis.<br />
11. Ahmed Saleem Mousa al-Astal, 24, Khan Younis (Suleimanâ??s brother)<br />
12. Mousa Mohammed Taher al-Astal, 50, Khan Younis.<br />
13. Ibrahim Khalil Qanan, 24, Khan Younis.<br />
14. Mohammad Khalil Qanan, 26, Khan Younis (Ibrahimâ??s brother).<br />
15. Ibrahim Sawali, 28, Khan Younis.<br />
16. Hamdi Badeaâ?? Sawali, 33, Khan Younis.<br />
17. Mohammad al-â??Aqqad, 24, Khan Younis.<br />
18. Ismael Hassan Abu Jameâ??, 19, Khan Younis.<br />
19. Hussein Odeh Abu Jameâ??, 75, Khan Younis.<br />
20. Abdullah Ramadan Abu Ghazal, 5, Beit Hanoun.<br />
21. Mohammad Ehsan Ferwana, 27, Khan Younis.<br />
22. Salem Qandil, 27, Gaza City. <br />
23. Amer al-Fayyoumi, 30, Gaza City.<br />
24. Raâ??ed az-Zourah, 32, Khan Younis<br />
<br />
<i>Killed Wednesday 7/9:</i><br />
<br />
1. Hamed Shihab, Journalist â?? Gaza.<br />
2. Salima al-â??Arja, 53, Rafah.<br />
3. Miriam â??Atiya al-â??Arja, 9, Rafah.<br />
4. Rafiq al-Kafarna, 30.<br />
5. Abdul-Nasser Abu Kweik, 60.<br />
6. Khaled Abu Kweik, 31.<br />
7. Mohammad Mustafa Malika, 18 months. <br />
8. Hanaâ?? Mohammed Fuâ??ad Malaka, 28 (Mohammadâ??s Mother), 27.<br />
9. Hatem Abu Salem, Gaza City.<br />
10. Mohammad Khaled an-Nimra, 22.<br />
11. Sahar Hamdan (al-Masry), 40, Beit Hanoun.<br />
12. Mohammad Ibrahim al-Masry, 14, Beit Hanoun.<br />
13. Amjad Hamdan, 23, Beit Hanoun.<br />
14. Hani Saleh Hamad, 57, Beit Hanoun.<br />
15. Ibrahim Hani Saleh Hamad, 20, Beit Hanoun.<br />
16. Mohammad Khalaf Nawasra, 4, al-Maghazi.<br />
17. Nidal Khalaf Nawasra, 5, al-Maghazi. <br />
18. Salah Awad Nawasra, 24, al-Maghazi. (father of Mohammad and Nidal)<br />
19. â??Aesha Najm al-Nawasra, 23, al-Maghazi (mother of Mohammad and Nidal, pregnant in the fourth month).<br />
20. Naifa Mohammed Zaher Farajallah, 80, al-Mughraqa.<br />
21. Amal Yousef Abdul-Ghafour, 20, Khan Younis.<br />
22. Nariman Jouda Abdul-Ghafour, 18 months, Khan Younis.<br />
23. Ibrahim Daoud al-Balâ??aawy. <br />
24. Abdul-Rahman Jamal az-Zamely.<br />
25. Ibrahim Ahmad â??Abdin, 42, Rafah. <br />
26. Mustafa Abu Murr, 20, Rafah. <br />
27. Khaled Abu Murr, 22, Rafah. <br />
28. Mazin Faraj Al-Jarba. <br />
29. Marwan Eslayyem.<br />
30. Raâ??ed Mohammed Shalat, 37, al-Nussairat.<br />
31. Yasmin Mohammad Matouq, 4, Beit Hanoun.<br />
<br />
<i>Killed Tuesday 7/8</i><br /><br />
1. Mohammad Shaâ??ban, 24, Gaza.<br />
2. Amjad Shaâ??ban, 30, Gaza. <br />
3. Khader al-Basheeleqety, 45, Gaza.<br />
4. Rashad Yassin, 27, Nusseirat.<br />
5. Mohammad Ayman â??Ashour, 15, Khan Younis.<br />
6. Riyadh Mohammad Kawareâ??, 50, Khan Younis. <br />
7. Bakr Mohammad Joudeh, 50, Khan Younis. <br />
8. Ammar Mohammad Joudeh, 26, Khan Younis. <br />
9. Hussein Yousef Kawareâ??, 13, Khan Younis.<br />
10. Bassem Salem Kawareâ??, 10, Khan Younis. <br />
11. Mohammad Ibrahim Kawareâ??, 50, Khan Younis. <br />
12. Mohammad Habib, 22, Gaza. <br />
13. Ahmed Mousa Habib, 16, Gaza.<br />
14. Saqr â??Aayesh al-â??Ajjoury, 22, Jabalia.<br />
15. Ahmad Nael Mahdi, 16, Gaza. <br />
16. Hafeth Mohammad Hamad, 26, Beit Hanoun.<br />
17. Ibrahim Mohammad Hamad, 26, Beit Hanoun.<br />
18. Mahdi Mohammad Hamad, 46, Beit Hanoun.<br />
19. Fawziyya Khalil Hamad, 62, Beit Hanoun. <br />
20. Donia Mahdi Hamad, 16, Beit Hanoun. <br />
21. Soha Hamad, 25, Beit Hanoun.<br />
22. Suleiman Salam Abu Sawaween, 22, Khan Younis.<br />
23. Siraj Eyad Abdul-â??Aal, 8, Khan Younis.<br />
24. Abdul-Hadi Soufi, 24, Rafah.<br />
<br />
<i>* the names with an asterisk have not yet been confirmed by Ministry of Health</i><br />
<hr />
<br />
Israeli soldiers killed by Palestinian resistance<br />
<br />
1. Unknown, 38, Erez military base, Tuesday, July 15th.<br />
2. Major Tsafrir Bar-Or, 32, killed Thursday, July 17th<br />
3. Captain Zvika Kaplan, 28, a resident of an illegal Israeli settlement in the West Bank, killed Thursday, July 17th<br />
4. Sergeant Oz Mendelovich, 21, killed Thursday, July 17th<br />
5. Sergeant Nissim Sean Carmeli, 21, killed Thursday, July 17th<br />
6. Sergeant Gilad Yaakobi, 21, killed Thursday, July 17th<br />
7. Eitan Barak, soldier killed Friday July 18th while invading Gaza.<br />
7. Major Amotz Greenberg, 45, killed Sat. July 19th while invading Gaza.<br />
8. Sergeant Adar Bersano, 20, killed Sat. July 19th while invading Gaza.<br />
9. Second Lieutenant Bar Rahav, 21, killed Sat. July 19th while invading Gaza.<br />
10. Sergeant Bnaya Rubel, 20, killed Sat. July 19th while invading Gaza.<br />

<br /><br />
One Israeli civilian was killed by a Palestinian shell:<br />
3. Auda al-Wadj, 32, Saturday July 19th<br /></DIV>
<!-- </List of Gaza Casualties obj id 2233> -->


         <?php
          global $editor_session, $pseudo_directory_offset;
          if(($editor_session->canEditLayout()|| $editor_session->canEditContent()) && ($editor_session->editor->allowedReadAccessTo("editdataobjects") || $editor_session->editor->allowedReadAccessTo("editobjdocument", 1)))
          {
          ?>
             <br>
            <a href="<?php echo $pseudo_directory_offset.$OSCAILT_SCRIPT ?>?obj_id=1&amp;obj_type=document&amp;target_id=2233&amp;action=edit&amp;site_id=1&amp;obj_language=en&amp;edit_entry_url=[<?=$_REQUEST["obj_id"]?>][][][][][]"><img hspace=1 border=0  align="left" title="Edit Static Document [List of Gaza Casualties] Configuration" alt="Edit Static Document [List of Gaza Casualties] Configuration" src="<?php echo $pseudo_directory_offset?>graphics/mediaicons/32x32/editorial2.png" /></a>
             
          <?
          }
          ?>
          