

<!-- <Benefit Album for IMEMC obj id 2235> -->
<P class='<?php echo $page_style; ?>'><a href='http://davidrovics.bandcamp.com/album/falasteen-habibti' class='<?php echo $page_style; ?>'><img class='<?php echo $page_style; ?>-thumbnail' src='<?php echo getResizedImageURL("http://imemc.org/attachments/aug2014/falasteen_habibti_sm.jpg", 0, 180, false, 0); ?>' alt='Benefit album by David Rovics: All proceeds benefit IMEMC' title='Benefit album by David Rovics: All proceeds benefit IMEMC' /></a></P>
<!-- </Benefit Album for IMEMC obj id 2235> -->

