<?php
//admin permissions are installation wide
//other permissions are on a per site section basis
$permissionsList = array(
"admin" => array(
array("edittopics", "Edit Story Topics"),
array("editregions", "Edit Regions"),
array("edittypes", "Edit Story Types"),
array("editlanguages", "Edit Story Languages"),
array("editroles", "Edit Roles"),
array("editeditors", "Edit Editors"),
array("editself", "Edit Self"),
array("viewstatus", "View Status and Oscailt Messages"),
array("editconfiguration", "Edit Site Configuration"),
array("editspam", "Edit Spam Configuration"),
array("editredirects", "Edit Smart URLs"),
array("editmonitor", "View Publishing IP addresses"),
array("editbannedips", "Manage Blocked IP addresses"),
array("bulkdelete", "Carry out Bulk Deletes"),
array("clearcache", "Clear Caches on the site"),
array("createsiteobjects", "Create new site sections"),
array("editsiteobjects", "Manage site section configuration"),
array("deletesiteobjects", "Delete site sections"),
array("importdataobjects", "Import From XML"),
array("exportdataobjects", "Export to XML Files"),
array("editdataobjects", "Manage all data objects"),
array("usehtml", "Use Approved HTML in forms"),
array("usefreehtml", "Use Any HTML in publish forms except scripts and dynamic code"),
array("usecode", "Use Code and scripts in forms"),
array("viewprotectedcategories", "View Articles that are classified in a protected Category"),
array("viewhiddencontent", "View Articles, comments and stories that have been hidden."),
array("ignoreattachmentlimits", "Ignore Size Restrictions on Attachments")
),
"editorial" => array(
array("editfeature", "Edit Front Page Feature"),
array("editowncontent", "Edit Your Own Stories and Comments"),
array("hidefeature", "Hide Front Page Feature"),
array("unhidefeature", "Unhide Front Page Feature"),
array("deletefeature", "Delete Front Page Feature"),
array("stickfeature", "Make Feature Sticky"),
array("unstickfeature", "Remove Stickiness from Feature"),
array("editstory", "Edit Story"),
array("hidestory", "Hide Story"),
array("unhidestory", "Unhide Story"),
array("deletestory", "Delete Story"),
array("downgradestory", "Downgrade Story"),
array("upgradestory", "Upgrade Story"),
array("stickstory", "Make Story Sticky"),
array("unstickstory", "Make Story Unsticky"),
array("editcomment", "Edit Comment"),
array("hidecomment", "Hide Comment"),
array("unhidecomment", "Unhide Comment"),
array("deletecomment", "Delete Comment"),
array("upgradecomment", "Upgrade Comment"),
array("copycomment", "Copy Comment"),
array("movecomment", "Move Comment"),
array("editattachment", "Edit Attachment"),
array("hideattachment", "Hide Attachment"),
array("unhideattachment","Unhide Attachment"),
array("deleteattachment", "Delete Attachment"),
array("copyattachment", "Copy Attachment"),
array("copyandunhideattachment", "Copy and Unhide Attachment"),
array("createattachment", "Create Attachment"),
array("moveattachment", "Move Attachment"),
array("featurizeattachment", "Featurise Attachment"),
array("unfeaturizeattachment",  "Unfeaturise Attachment"),
array("swapattachment",  "Swap Attachment"),
array("lockfeature", "Lock Feature"),
array("unlockfeature", "Unlock Feature"),
array("translatefeature", "Link Translated Feature"),
array("lockstory", "Lock Story"),
array("unlockstory", "Unlock Story"),
array("translatestory", "Link Translated Story"),
array("commentonlocked", "Write Comments to Stories that have been locked"),
array("multihidecomment", "Hide Multiple Comments in one go"),
array("multiunhidecomment", "Unhide Multiple Comments in one go"),
array("multideletecomment", "Delete Multiple Comments in one go"),
array("multihidestory", "Hide Multiple Stories in one go"),
array("multiunhidestory", "Unhide Multiple Stories in one go"),
array("multistickstory", "Make multiple stories sticky in one go"),
array("multiunstickstory", "Make Multiple stories sticky in one go"),
array("multilockstory", "Lock Multiple Stories in one go"),
array("multiunlockstory", "Unlock Multiple Stories in one go"),
array("overrideautohide", "Publish Directly Without Approval on publish pages that require approval."),
),
"site" => array(
   array("editsitefiles", "Manage Site Files"),
   array("publishsite", "Publish Updated Site Objects"),
   array("exportsite", "Export Site to file"),
   array("viewprotected", "View Protected Objects (you must set this to allow the role to view the data objects for the site)")
));
?>
