<?php global $pseudo_directory_offset; $site_file_store = $pseudo_directory_offset."attachments/sites/default/"; 
$oscailt_page_setting = Array("site_module_settings" => Array("siteobject" => "1", "newswireobject" => "2126", "articleobject" => "53", "featureobject" => "54", "galleryobject" => "64", "searchobject" => "2212", "archiveobject" => "55", "contactobject" => "84", "commentsobject" => "", "publishobject" => "57", "eventsobject" => "58"), "site_mail_settings" => Array("to" => "news@imemc.org", "from" => "site@imemc.org", "subject_prefix" => "Article edit:", "replyto" => "news@imemc.org", "level" => "none"), "site_filters" => Array("topic" => Array("0" => "*"), "region" => Array("0" => "20", "1" => "19", "2" => "18", "3" => "17", "4" => "16", "5" => "15", "6" => "14", "7" => "13", "8" => "12", "9" => "11", "10" => "10", "11" => "9", "12" => "8", "13" => "7", "14" => "6", "15" => "5", "16" => "4", "17" => "3", "18" => "2", "19" => "1"), "language" => Array("0" => "en"), "type" => Array("0" => "*"), "author" => ""), "obj_id" => "2038", "obj_type" => "DOCUMENT", "site_id" => "1");
$oscailt_story_query = new StoryQuery();
$oscailt_story_query->loadFormValues();
$PAGE_LAYOUT_ID = 2032; ?>
<?
         addToPageDescription("The IMEMC is a media collective. We are independent journalists producing and distributing the authentic voices of the people.  We are located in Beit Sahour, in the Occupied West Bank, and we welcome new volunteers and contributors.");
      addToPageTitle("Editorial");
         addToPageDescription("The International Middle East Media Center is built on the foundation of an open and democratic newswire. We want to see and hear real stories, news, and opinions from users of the site, both from inside Palestine, and in the rest of the world.  At the same time, we are committed to an accurate recounting of events that doesn\'t sensationalize or judge, but presents the reality of the conflict as it occurs in the occupied Palestinian territories, where our collective is located.

Anyone is welcome to contribute to the site - if you are interested in contributing, please read through the editorial policy and make sure your article is in adherence, then send it to news@imemc.org"); ?>

<!-- <editorial obj id 2038> -->
<h1 class='indypagebody'>International Middle East Media Center's Editorial Guidelines</h1><BLOCKQUOTE class='indypagebody'>The International Middle East Media Center is built on the foundation of an open and democratic newswire. We want to see and hear real stories, news, and opinions from users of the site, both from inside Palestine, and in the rest of the world.  At the same time, we are committed to an accurate recounting of events that doesn\'t sensationalize or judge, but presents the reality of the conflict as it occurs in the occupied Palestinian territories, where our collective is located.

Anyone is welcome to contribute to the site - if you are interested in contributing, please read through the editorial policy and make sure your article is in adherence, then click publish and fill out the form to contribute your article to the site.</BLOCKQUOTE><DIV class='indypagebody'><img align=right src=attachments/sites/site_1/indymedia_dalek.jpg>
<p><b>In general, posts may be removed for any of the following reasons:</b></p> 

<ol> 

<li><b>Comments, not news</b>. If there is a recently published story on the same topic as, or one closely related to your post, then it should be published as a comment on the existing story. Comments belong with the story being discussed - to have your say in response to a story on the site, use the \"<i>add your comments</i>\" link at the bottom of each story</li> 

<li><b>Duplicate posts</b>. Make sure you\'ve read the newswire and that the story doesn\'t appear there already. Also make sure that you haven\'t posted the same comment on multiple stories</li> 

<li><b>Infactual or obviously false posts</b>. The onus is on the author to check and confirm facts - if a clear factual error is brought to our attention it will be removed.</li> 

<li><b>Libelous or slanderous posts</b>. Choose your language carefully. Do not make allegations against named individuals unless you can substantiate them. Posts which contain personal abuse against named individuals, rather than against their arguments or their political affiliation, will be removed without delay, particularly if those individuals are not public figures. \'<i>Play the ball, not the player</i>\'.</li> 

<li><b>Discriminatory or hateful posts</b>. Posts that contain 

explicitly racist, sexist or homophobic views will be removed. We don\'t 

oppose free speech for people with hateful views, we\'re just not going 

to provide them with a platform for distributing those views.</li> 

<li><b>Advertising or other inappropriate content</b>. Advertising of commercial products or services, particularly when they are sold on a for-profit basis.</li> 

<li><b>Cross-posting to multiple Independent Media Centers (IMCs)</b>. Posts that are available 

elsewhere on the Indymedia network (on at least two other IMCs) shall 

be deleted, although in cases where the article is particularly 

relevant to Irish readers, it may be allowed to remain at the 

discretion of the editorial collective.</li> 

<li><b>Articles which have no News Content</b>. Although we aim to have a broad tolerance for all types of news postings, there are limits. In 

particular, the following types of article are not considered to be news: <ul><li>Incomprehensible \'gobbledygook\' postings</li> 

<li>Asking of questions - particular or general questions without any other content - e.g. this type of thing: \"<i>Anyone know when X is on?</i>\" or \"<i>What do you think of YYY policy on ZZZZ?</i>\"</li> 

<li>Articles which consist entirely of unsubstantiated opinions or personal musings 

without any supporting evidence or other content. For example : \'<i>I think Fianna Fail are criminals</i>\'</li> 

<li>Petitions</li></ul> 

</li><li><b>Impersonation</b>. Articles or comments which impersonate other indymedia users by adoption of their names or regular pseudonyms</li> 

<li><b>Fascists</b>. All content expressing fascist views or written by active fascists, or expressing revisionist / holocaust denial 

positions, or linking to a fascist site. We will not provide a platform for fascist recruitment</li> 

<li><b>Trolling</b>. Comments which consist entirely of abuse towards any group, individual, or article without attempting to situate this in 

the context of the particular article or debate arising out of that article. So for example, a comment which simply says: \"<i>the Popular Front of Judea are wankers</i>\" will be deleted, while a comment that says: \"<i>The fact that the PFJ have refused this offer of an alliance shows them to 

be hypocritical wankers in the light of what they have said before</i>\", <b>might</b> remain</li> 

<li><b>Continuing debates across multiple articles</b>. Indymedia is 

not a bulletin board. All comments should directly relate to the 

article or preceding comments. Users should refrain from constantly 

bringing up points from previous threads, unless they have a close 

relevance to the new article. Users should also note that repetitive 

demands of another user to answer a particular question or point is a 

reason for deletion especially when it occurs across multiple threads. </li> 

<li><b>Persistent Abuse</b>. Users who persistently refuse to abide by IMC policy are liable to have any and all of their contributions removed</li> 

<li><b>Cut and pastes</b>. Posts that are publicly available elsewhere 

on the internet, or in the mainstream media. We do realise, however, 

that there can sometimes by a strong case for articles published 

elsewhere to be brought to the attention of IMC readers. In these 

cases, we ask contributors to write an original introduction to the 

article, highlighting its relevance to Irish indymedia readers and 

include a link to the article. Users can also choose post a short note 

and a link in the Media Updates link at the top of the newswire. In 

particular, articles that consist of an original introduction and 

contain several links to articles containing background information 

stand a good chance of being made into front-page features</li> 

<li><b>Comments on editorial policy</b>. Users can appeal for or against deletions by contacting the editors using the \'<i>Contact Us</i>\' 

link at the top of the front page. Editorial actions are debated on the 

editorial list and users can join the list and join in the frequent 

debates on deletions there. Commentary on IMC Ireland editorial policy 

on the newswire will be removed</li> 

<li><b>Comments that refer to Deleted Posts</b>. Comments referring to something that a user can\'t see as it has been deleted will also be removed.</li> 

</ol> 

<p>A record of all editorial actions, which editor performed the action and the reason for it are sent to the <a href=\"http://lists.indymedia.org/mailman/listinfo/imc-palestine\">mailing list</a> 

which anybody can join. So if you want to keep an eye on the evil 

censorships of the imc-cabal, you know what to do. Subscribing to this 

list means you will see all articles and comments which have been 

hidden and the reason why they were hidden. After subscribing, you can 

then go through the <a href=\"http://lists.indymedia.org/mailman/listinfo/imc-palestine\">archives</a> of the list to see all past editorial actions.</p> 

<p>Guidelines are subject to constant review by the <a href=\"http://lists.indymedia.org/mailman/listinfo/imc-palestine\">editorial list</a>. 

If you think that these guidelines are not being enforced (or are being 

abused) join the editorial list and discuss it there. If you think an 

article that you have posted has been unfairly deleted, the editorial 

list is the place to bring it up but make sure that you have read and 

understood the editorial policy beforehand. As with the newsire list, 

you can go through the <a href=\"http://lists.indymedia.org/mailman/listinfo/imc-palestine\">archives</a> 

to see why and how these guidelines were formulated. This list is also 

used to put together the front page features. If you\'d rather not 

subscribe to the editorial list, you can just use the <a href=\"contact.php\">contact form</a> 

</p><p>to send a message to the editors making sure to provide your email 

address so that you can be CCed on all emails regarding the query. 

</p><p><big><b>Legal Stuff</b></big></p><p>We think stories contributed to 

this site should be free for non-profit re-use. Copy left is an idea 

central to indymedia (for more information, check out <a href=\"http://www.opencontent.org/\">http://www.opencontent.org/</a>). 

If you want to change that for your story, please give your 

conditions in the summary. 

</p><p>After stories have been published, they may be edited, linked or 

even deleted by the collective running this site. Please read our <a href=\"privacy.php\">privacy</a> and <a href=\"disclaimer.php\">disclaimer</a> 

statements. <br>&nbsp;</p></DIV>
<!-- </editorial obj id 2038> -->

<?php getPageLanguageOptions("en", Array("0" => "en", "1" => "sp"), "2038"); ?>
         <?php
          global $editor_session, $pseudo_directory_offset;
          if(($editor_session->canEditLayout()|| $editor_session->canEditContent()) && ($editor_session->editor->allowedReadAccessTo("editdataobjects") || $editor_session->editor->allowedReadAccessTo("editobjdocument", 1)))
          {
          ?>
             <br>
            <a href="<?php echo $pseudo_directory_offset.$OSCAILT_SCRIPT ?>?obj_id=1&amp;obj_type=document&amp;target_id=2038&amp;action=edit&amp;site_id=1&amp;obj_language=en&amp;edit_entry_url=[<?=$_REQUEST["obj_id"]?>][][][][][]"><img hspace=1 border=0  align="left" title="Edit Static Document [editorial] Configuration" alt="Edit Static Document [editorial] Configuration" src="<?php echo $pseudo_directory_offset?>graphics/mediaicons/32x32/editorial2.png" /></a>
             
          <?
          }
          ?>
          